twosixlabs/armory

armory/eval_scripts/carlini_wagner_attack_targeted.py
armory/eval_scripts/fgm_attack.py
armory/eval_scripts/fgm_attack_binary_search.py
armory/eval_scripts/poisoning_attack_backdoor.py
armory/eval_scripts/transfer_attack.py
armory/eval_scripts/transform_defense.py
examples/fgm_attack.json
examples/fgm_attack_binary_search.json

Enhanced logging in eval-scripts. Added clipping option to classifier in FGM and FGM binary search attacks.

Enhanced logging, clipping

---

.github/workflows/ci_test.yml
.github/workflows/release.yml
Dockerfile
README.md
armory/__init__.py
armory/__main__.py
examples/backdoor_poisoning.json
examples/carlini_wagner_l2_targeted.json
examples/carlini_wagner_linf_targeted.json
examples/fgm_attack.json
examples/fgm_attack_binary_search.json
examples/transfer_attack.json
examples/transform_defense.json
tests/test_data/missing_eval.json
tests/test_docker_management.py

After this I will cut a 0.3 branch and tag

Prep 0.3 branch

---

.github/workflows/ci_test.yml
Dockerfile
README.md
armory/__init__.py
armory/__main__.py
armory/data/datasets.py
examples/backdoor_poisoning.json
examples/carlini_wagner_l2_targeted.json
examples/carlini_wagner_linf_targeted.json
examples/fgm_attack.json
examples/fgm_attack_binary_search.json
examples/transfer_attack.json
examples/transform_defense.json
tests/test_data/missing_eval.json
tests/test_docker_management.py

Few bumps in the road for the first release process. Should be all good going forward:
https://pypi.org/project/armory-testbed/0.3.3/

Update versions on master branch

---

examples/README.md

It was bothering me during the presentation. This is for me mostly.

really small syntax change

---

armory/eval/evaluator.py

https://jupyterlab.readthedocs.io/en/stable/

Launch jupyter lab instead of notebook

---

armory/paths.py

Closes #159 
Considered putting in a few lines to create this field in already existing configs but #162 will require users to delete existing configs anyway.

Enable a cached dataset directory

---

.github/workflows/release.yml

Correct release script which didn't get cherry-picked to master

BLD: Fix release script

---

.github/workflows/ci_test.yml

I think this is how this works.

added json-format to ci_test

---

README.md

Docker docs

---

.github/workflows/release.yml
Dockerfile
README.md
armory/__init__.py

* Updates docker to build/publish automatically in release
* Updates version to 0.4.0
Closes #176 
Closes #151

Automate docker build and publish

---

armory/__main__.py
armory/eval/evaluator.py
armory/utils/__init__.py
armory/utils/docker_api.py

update docker pull

---

.github/workflows/release.yml
armory/__init__.py
armory/art_experimental/__init__.py
armory/data/__init__.py

Update inits so there are no extra dependencies.

---

armory/data/datasets.py
test-requirements.txt
tests/test_dataset.py

Add German traffic sign dataset.

German traffic sign dataset

---

.github/workflows/ci_test.yml

Run CI tests on release branches

---

armory/data/datasets.py
tests/test_dataset.py

Update to RGB adversarial dataset

---

.github/workflows/ci_test.yml
.github/workflows/release.yml
.yamllint
STYLE.md
test-requirements.txt
tools/pre-commit.sh

Lint yaml files, add linter to pre-commit tool. Closes #199.

Lint yaml files, add linter to pre-commit tool

---

.github/workflows/release.yml

Clean up release script on 0.5

---

armory/data/datasets.py

Closes Issue #209. Note that users who already have downloaded external datasets may have additional downloads given the new paths.

Standardize dataset directory structure (Issue #209)

---

docker/Dockerfile

Dockerfile base updated for new datasets

---

armory/data/datasets.py
armory/data/resisc45/resisc45_dataset_partition.py
armory/data/resisc45/resisc45_split.py
armory/data/tfds_checksum.py
armory/data/url_checksums/resisc45_split.txt
armory/data/utils.py
tests/test_dataset.py

rebased off master, using generator framework

Resisc45 generator

---

armory/data/datasets.py
armory/data/librispeech/librispeech_split.py
armory/data/url_checksums/librispeech_split.txt
test-requirements.txt
tests/test_dataset.py

Closes Issue #222. Needs to be rebased -- was working on a stale version of master.

Librispeech

---

armory/data/datasets.py
tests/test_dataset.py

Ucf101 save

---

armory/data/datasets.py
tests/test_dataset.py

Updates German traffic sign dataset method to return an ArmoryDataGenerator. Closes Issue #242.

German traffic sign generator

---

armory/data/datasets.py
tests/test_dataset.py

Update to TFDS for Imagenette

---

armory/baseline_models/keras/keras_cifar.py
armory/baseline_models/keras/keras_inception_resnet_v2.py
armory/baseline_models/keras/keras_mnist.py
armory/baseline_models/keras/keras_resnet50.py
armory/data/datasets.py
tests/test_dataset.py

Imagenet adv generator

---

armory/__init__.py
tests/test_configs/fgm_attack_test.json
tests/test_configs/missing_eval.json

Master should be on version ahead of release

Bump version on master

---

armory/baseline_models/pytorch/imagenet.py

Utilize clip_values for pytorch

---

armory/utils/configuration.py
tests/test_configs/missing_eval.json

Add batch_size to dataset config verification

---

armory/baseline_models/pytorch/pytorch_mnist.py
tests/test_pytorch/test_pytorch_models.py
tests/test_tf1/test_keras_models.py

Matches the same network for Keras mnist.

Add pytorch mnist model

---

armory/baseline_models/pytorch/pytorch_cifar.py
tests/test_pytorch/test_pytorch_models.py

Matches the Keras implementation

Add pytorch cifar model

---

armory/data/cached_url_checksums/librispeech_dev_clean_split.txt
armory/data/cached_url_checksums/resisc45_split.txt
armory/data/cached_url_checksums/ucf101.txt
armory/data/datasets.py
armory/data/utils.py

Closes #270. Uses same hash/URL format as TFDS.

Ds tfrecord cache

---

armory/data/datasets.py
armory/data/german_traffic_sign/german_traffic_sign.py
armory/data/url_checksums/german_traffic_sign.txt

German tfds

---

armory/data/cached_url_checksums/librispeech_dev_clean_split.txt

Update Librispeech cached tfrecords to correspond to updated dataset from #306

Update Librispeech cached tfrecords

---

armory/data/README.md
armory/data/datasets.py
armory/data/digit/digit.py
armory/data/url_checksums/digit.txt

Additionally removes the numpy generator based material and other redundant imports.

Tfds digit rebase extra

---

armory/data/README.md
armory/data/adversarial/imagenet_adversarial.py
armory/data/datasets.py
armory/data/url_checksums/imagenet_adversarial.txt

Rebased to avoid merge conflict.

Adversarial tfds rebase

---

armory/data/cached_s3_checksums/librispeech_dev_clean_split.txt
armory/data/cached_s3_checksums/resisc45_split.txt
armory/data/cached_s3_checksums/ucf101.txt
armory/data/cached_url_checksums/librispeech_dev_clean_split.txt
armory/data/cached_url_checksums/resisc45_split.txt
armory/data/cached_url_checksums/ucf101.txt
armory/data/datasets.py
armory/data/utils.py
docker/Dockerfile

Closes #317. Will be more user-friendly with Issue #318 resolved (separate PR).

Switch from curl to boto3 for downloads

---

tools/format_json.py
tools/pre-commit.sh

I'm not sure why this isn't in our pre-commit.sh, as it is in our ci testing.

Pre commit json

---

.github/workflows/ci_test.yml

Testing to see if we see a performance improvement on test cases

Utilize docker build kit

---

armory/data/cached_s3_checksums/cifar10.txt
armory/data/cached_s3_checksums/digit.txt
armory/data/cached_s3_checksums/german_traffic_sign.txt
armory/data/cached_s3_checksums/imagenet_adversarial.txt
armory/data/cached_s3_checksums/imagenette.txt
armory/data/cached_s3_checksums/mnist.txt
armory/data/datasets.py

Extend tfrecord cache to all datasets

---

.github/workflows/ci_test.yml

This was a bug in checkout@v1:
https://github.com/actions/checkout/issues/23

Allow triggering a re-test in GitHub actions

---

armory/baseline_models/keras/cifar.py
armory/baseline_models/keras/inception_resnet_v2.py
armory/baseline_models/keras/mnist.py
armory/baseline_models/keras/resisc45.py
armory/baseline_models/keras/resnet50.py
armory/baseline_models/pytorch/cifar.py
armory/baseline_models/pytorch/mnist.py
armory/baseline_models/pytorch/resnet50.py
armory/data/model_weights.py
armory/utils/config_loading.py
tests/configs/fgm_attack_test.json
tests/configs/resisc45_scenario_baseline.json
tests/conftest.py
tests/test_docker/test_weight_download.py
tests/test_host/test_weight_download.py
tests/test_pytorch/test_pytorch_models.py
tests/test_tf1/test_keras_models.py
tests/test_tf1/test_tf1_models.py
tests/test_tf2/test_tf2_models.py

Closes #210 
Closes #263
Will incorporate into #316 and #333 after this merges

Standardize model weights downloading and loading

---

tests/test_docker/test_dataset.py
tests/test_docker/test_supported_datasets.py
tests/test_docker/test_weight_download.py
tests/test_host/test_config_verification.py
tests/test_host/test_external_repo.py
tests/test_pytorch/test_pytorch_models.py
tests/test_tf1/test_keras_models.py
tests/test_tf1/test_tf1_models.py
tests/test_tf2/test_tf2_models.py

Closes #337 
Simplifies this quite a bit and allows for us to use a number of pytest extensions now:
https://docs.pytest.org/en/latest/assert.html

Standardize on using pytest

---

armory/eval/evaluator.py
docs/docker.md

@ng390 I'd like your take on this soon, as this makes it much nicer to run these tests on our gpu servers.

docker and writing

---

armory/scenarios/configs/gtsrb_scenario_baseline.json
armory/scenarios/gtsrb_scenario.py

Poisoning scenario standardization/refactoring

Poisoning scenario refactoring

---

armory/baseline_models/keras/cifar.py
armory/baseline_models/keras/densenet121_resisc45.py
armory/baseline_models/keras/gtsrb_micronnet.py
armory/baseline_models/keras/inception_resnet_v2.py
armory/baseline_models/keras/librispeech_spectrogram.py
armory/baseline_models/keras/mnist.py
armory/baseline_models/keras/resnet50.py
armory/baseline_models/pytorch/cifar.py
armory/baseline_models/pytorch/mnist.py
armory/baseline_models/pytorch/resnet50.py
armory/baseline_models/pytorch/sincnet.py
armory/baseline_models/pytorch/ucf101_mars.py
armory/scenarios/configs/cifar10_baseline.json
armory/scenarios/configs/gtsrb_scenario_baseline.json
armory/scenarios/configs/librispeech_dev_clean_baseline_raw_sincnet.json
armory/scenarios/configs/librispeech_dev_clean_baseline_spectrogram.json
armory/scenarios/configs/mnist.json
armory/scenarios/configs/resisc45_baseline_densenet121.json
armory/scenarios/configs/ucf101_baseline_finetune.json
armory/scenarios/configs/ucf101_baseline_pretrained.json

Add docstrings and MITRE attribution

---

armory/scenarios/configs/librispeech_dev_clean_baseline_raw_sincnet.json
armory/scenarios/configs/ucf101_baseline_finetune.json
armory/scenarios/configs/ucf101_baseline_pretrained.json

Blocked on this PR https://github.com/hkakitani/SincNet/pull/2

update external repo pointing

---

armory/data/utils.py

Download using requests/tqdm

---

README.md

More information based on feedback from external users.

Add additional documentation info

---

armory/scenarios/configs/cifar10_baseline.json
armory/scenarios/configs/cifar10_defended_example.json
armory/scenarios/configs/gtsrb_scenario_baseline.json
armory/scenarios/configs/librispeech_dev_clean_baseline_raw_sincnet.json
armory/scenarios/configs/librispeech_dev_clean_baseline_spectrogram.json
armory/scenarios/configs/mnist_baseline.json
armory/scenarios/configs/resisc45_baseline_densenet121.json
armory/scenarios/configs/ucf101_baseline_finetune.json
armory/scenarios/configs/ucf101_baseline_pretrained.json
docs/docker.md
tests/scenarios/pytorch/image_classification.json
tests/scenarios/pytorch/image_classification_pretrained.json
tests/scenarios/tf1/image_classification.json
tests/scenarios/tf1/image_classification_pretrained.json

Add "gpus" field to config files

Config standardization

---

armory/data/utils.py

Partial resolution of Issue #356

requests download without SSL certificate verification

---

armory/scenarios/configs/cifar10_baseline.json
armory/scenarios/image_classification.py
armory/utils/metrics.py
tests/test_docker/test_metrics.py

Metrics refactor

---

armory/data/utils.py

Fix for SSL issue inside container

---

armory/data/utils.py

Suppress requests warnings for unverified Https request in download-data

Suppress requests warnings for unverified Https request

---

armory/scenarios/audio_classification.py
armory/scenarios/gtsrb_scenario.py
armory/scenarios/image_classification.py
armory/scenarios/ucf101.py
armory/utils/config_loading.py

Add defenses

---

armory/scenarios/download_configs/scenarios-set1.json

Update weight file paths in download config

Update weight file paths

---

.github/workflows/ci_test.yml
armory/__init__.py
scenario_configs/cifar10_baseline.json
scenario_configs/cifar10_defended_example.json
scenario_configs/gtsrb_scenario_baseline.json
scenario_configs/librispeech_baseline_sincnet.json
scenario_configs/mnist_baseline.json
scenario_configs/resisc45_baseline_densenet121.json
scenario_configs/ucf101_baseline_finetune.json
scenario_configs/ucf101_baseline_pretrained.json
tests/scenarios/broken/invalid_module.json
tests/scenarios/broken/missing_scenario.json
tests/scenarios/pytorch/image_classification.json
tests/scenarios/pytorch/image_classification_pretrained.json
tests/scenarios/tf1/image_classification.json
tests/scenarios/tf1/image_classification_pretrained.json

Removed CI testing since docker won't be available given that it's not built with `-dev`

Update to rc0

---

scenario_configs/resisc45_baseline_densenet121_finetune.json

Closes #424 
Blocked waiting for h5 file

Add finetune config for resisc

---

armory/__main__.py

Path fix for download data for release

Path fix for download data for release

---

tests/test_pytorch/test_pytorch_models.py

Hopefully this will prevent these stochastic errors in testing

Lowering the bar for pytorch test

---

armory/__main__.py

Update help string

---

armory/__init__.py
scenario_configs/cifar10_baseline.json
scenario_configs/cifar10_defended_example.json
scenario_configs/gtsrb_scenario_baseline.json
scenario_configs/librispeech_baseline_sincnet.json
scenario_configs/mnist_baseline.json
scenario_configs/resisc45_baseline_densenet121.json
scenario_configs/resisc45_baseline_densenet121_finetune.json
scenario_configs/ucf101_baseline_finetune.json
scenario_configs/ucf101_baseline_pretrained.json
tests/scenarios/broken/invalid_module.json
tests/scenarios/broken/missing_scenario.json
tests/scenarios/pytorch/image_classification.json
tests/scenarios/pytorch/image_classification_pretrained.json
tests/scenarios/tf1/image_classification.json
tests/scenarios/tf1/image_classification_pretrained.json
tests/test_host/test_config_verification.py

Move master to 0.7-dev

---

armory/scenarios/video_ucf101_scenario.py

Fixes #396 
This doesn't fix the broader issue of differenet predict/fit, but it does make the attack work. The broader issue is documented in #417 
Probably merge in the 0.7.0-dev before doing anything else, yes?

UCF101 - predict on adversarial

---

docker/Dockerfile
docker/pytorch-dev/Dockerfile
docker/pytorch/Dockerfile
docker/tf1-dev/Dockerfile
docker/tf1/Dockerfile
docker/tf2-dev/Dockerfile
docker/tf2/Dockerfile

Smaller docker images

---

armory/__main__.py

Make launch with no args a no-op command

---

docs/scenarios.md

Add placeholders for scenario information

---

armory/__main__.py
armory/docker/management.py
docs/configuration_files.md
docs/docker.md
docs/index.md

Enable custom docker images

---

.github/workflows/ci_test.yml
armory/__main__.py
armory/docker/host_management.py
armory/eval/evaluator.py
armory/paths.py
armory/scenarios/base.py
armory/utils/config_schema.json
docs/configuration_files.md
docs/docker.md
host-requirements-conda.sh
host-requirements.txt

Run armory without docker

---

armory/__main__.py

Part of clean-up for new launching refactor

Standardize how we launch from armory main

---

armory/__main__.py
armory/data/utils.py
armory/eval/evaluator.py
armory/paths.py

Verify ssl config

---

armory/eval/evaluator.py

Pass nvidia runtime if needed

---

armory/data/datasets.py
armory/utils/config_loading.py

Enable multiple workers in PyTorch DataLoader

---

armory/baseline_models/keras/gtsrb_micronnet.py

Minor update to the GTSRB preprocessing function to use PIL

Update poison model preprocessing

---

docs/scenarios.md

Added baseline performance values for UCF101 scenario

updated baseline performance for UCF101

---

armory/art_experimental/defences/jpeg_compression_5d.py
scenario_configs/ucf101_baseline_adversarial.json

Implemented art_experimental.defences.JpegCompression5D as the baseline defense for video UCF101 scenario

Adds art_experimental.defences.JpegCompression5D

---

armory/__main__.py
armory/eval/evaluator.py

Add --gpus flag to exec, launch, and run

---

armory/scenarios/poisoning_gtsrb_scenario.py
docs/configuration_files.md
scenario_configs/gtsrb_scenario_baseline.json

Enable poison scenario to have no filtering component

---

armory/baseline_models/tf_graph/mnist.py
tests/scenarios/tf1/image_classification_tfgraph.json
tests/test_tf1/test_keras_models.py
tests/test_tf1/test_tf1_models.py

Add TF graph example

---

README.md
docs/index.md

Docs update for armory run --interactive

---

armory/scenarios/base.py
armory/utils/external_repo.py
docs/external_repos.md
docs/getting_started.md
scenario_configs/librispeech_spectrogram_external_repo.json

Closes #516 
Closes #539 
Closes #510
* Improve access pattern for external repo dirs

Improve external repo mangement

---

armory/eval/evaluator.py

Add token authentication for jupyter launch

---

armory/__main__.py

Update download config path in helpstring

---

armory/scenarios/poisoning_gtsrb_scenario.py
scenario_configs/gtsrb_scenario_baseline.json

Update poisoning scenario

---

armory/data/utils.py
tests/test_docker/test_weight_download.py

Improve error message for missing weights on S3

---

armory/eval/evaluator.py

Improve error message for trying to pull dev containers

---

tests/test_docker/test_dataset.py

Add tests for adversarial datasets

---

docs/external_repos.md

Document how to add non-standard python paths when needed

---

scenario_configs/librispeech_baseline_sincnet.json
scenario_configs/librispeech_baseline_sincnet_adversarial.json
scenario_configs/librispeech_spectrogram_external_repo.json
scenario_configs/resisc45_baseline_densenet121_adversarial.json
scenario_configs/ucf101_baseline_adversarial.json
scenario_configs/ucf101_baseline_finetune.json
scenario_configs/ucf101_baseline_pretrained.json
tests/scenarios/broken/invalid_module.json

Closes https://github.com/twosixlabs/armory/issues/574

Remove budget from configuration files

---

armory/data/adversarial/imagenet_adversarial.py
armory/data/adversarial_datasets.py
armory/data/cached_s3_checksums/imagenet_adversarial.txt
tests/test_docker/test_dataset.py
tests/test_tf1/test_keras_models.py

Imagenet adversarial paired samples

---

armory/scenarios/poisoning_gtsrb_scenario.py

Poisoning scenario: update randomization

---

armory/utils/metrics.py
tests/test_docker/test_metrics.py

SNR perturbation metrics

---

docs/scenarios.md

Updated results for image scenario include:
- benign and attacked accuracy for undefended model
- benign and attacked accuracy for JpegCompression defended model

Added baseline performance for image scenario

---

armory/__main__.py
armory/eval/evaluator.py

Fix port mapping for armory launch and armory run

---

docs/adversarial_datasets.md
docs/datasets.md

- added documentation of delivered adversarial datasets
- added hyperlinks between datasets.md and adversarial_datasets.md

Adversarial datasets docs

---

docs/baseline_models.md
docs/faqs.md
docs/getting_started.md
docs/index.md
docs/metrics.md
docs/scenarios.md

Minor documentation updates

---

armory/scenarios/audio_classification.py
armory/scenarios/image_classification.py
armory/scenarios/video_ucf101_scenario.py
armory/utils/config_schema.json
docs/configuration_files.md
docs/scenarios.md
scenario_configs/cifar10_baseline.json
scenario_configs/cifar10_defended_example.json
scenario_configs/librispeech_baseline_sincnet.json
scenario_configs/librispeech_baseline_sincnet_adversarial.json
scenario_configs/librispeech_spectrogram_external_repo.json
scenario_configs/mnist_baseline.json
scenario_configs/resisc45_baseline_densenet121.json
scenario_configs/resisc45_baseline_densenet121_adversarial.json
scenario_configs/resisc45_baseline_densenet121_finetune.json
scenario_configs/ucf101_baseline_adversarial.json
scenario_configs/ucf101_baseline_finetune.json
scenario_configs/ucf101_baseline_pretrained.json

PGD fix (also applies to other attacks that need ground truth labels)

---

armory/__main__.py
armory/eval/evaluator.py
armory/scenarios/base.py
armory/utils/config_schema.json
docs/configuration_files.md
scenario_configs/cifar10_baseline.json
scenario_configs/cifar10_defended_example.json
scenario_configs/gtsrb_scenario_baseline.json
scenario_configs/librispeech_baseline_sincnet.json
scenario_configs/librispeech_baseline_sincnet_adversarial.json
scenario_configs/librispeech_spectrogram_external_repo.json
scenario_configs/mnist_baseline.json
scenario_configs/resisc45_baseline_densenet121.json
scenario_configs/resisc45_baseline_densenet121_adversarial.json
scenario_configs/resisc45_baseline_densenet121_finetune.json
scenario_configs/ucf101_baseline_adversarial.json
scenario_configs/ucf101_baseline_finetune.json
scenario_configs/ucf101_baseline_pretrained.json
tests/scenarios/broken/invalid_dataset_framework.json
tests/scenarios/broken/invalid_module.json
tests/scenarios/broken/missing_scenario.json
tests/scenarios/pytorch/image_classification.json
tests/scenarios/pytorch/image_classification_pretrained.json
tests/scenarios/tf1/image_classification.json
tests/scenarios/tf1/image_classification_pretrained.json
tests/scenarios/tf1/image_classification_tfgraph.json

Fixes #584. Draft (1) because wanted to discuss timestamp in directory and filename (2) need to update docs.

More user friendly and configurable output filename/directory

---

docs/datasets.md

Dataset split and preprocessing docs

---

armory/utils/config_loading.py

Only question would be whether this should instead raise an error?

Add warning for evaluating model without weights nor training

---

STYLE.md
armory/scenarios/base.py
armory/utils/config_schema.json
armory/utils/external_repo.py
docs/external_repos.md
tests/test_host/test_external_repo.py

Enable multiple external repos

---

scenario_configs/cifar10_baseline.json
scenario_configs/cifar10_defended_example.json
scenario_configs/gtsrb_scenario_baseline.json
scenario_configs/librispeech_baseline_sincnet.json
scenario_configs/librispeech_spectrogram_external_repo.json
scenario_configs/mnist_baseline.json
scenario_configs/resisc45_baseline_densenet121.json
scenario_configs/resisc45_baseline_densenet121_adversarial.json
scenario_configs/resisc45_baseline_densenet121_finetune.json
scenario_configs/ucf101_baseline_adversarial.json
scenario_configs/ucf101_baseline_finetune.json
scenario_configs/ucf101_baseline_pretrained.json
tests/scenarios/broken/invalid_dataset_framework.json
tests/scenarios/broken/invalid_module.json
tests/scenarios/broken/missing_scenario.json
tests/scenarios/pytorch/image_classification.json
tests/scenarios/pytorch/image_classification_pretrained.json
tests/scenarios/tf1/image_classification.json
tests/scenarios/tf1/image_classification_pretrained.json
tests/scenarios/tf1/image_classification_tfgraph.json

Add ART default parameters to scenario attacks and defenses

---

armory/data/datasets.py
armory/scenarios/poisoning_gtsrb_scenario.py

Partially resolves #598. Creates reproducible poison splits dependent on the two seeds to the PRGs.

Pre-defined poisoned splits

---

armory/baseline_models/pytorch/sincnet_full.py
armory/scenarios/audio_classification.py
armory/utils/config_loading.py
scenario_configs/librispeech_baseline_sincnet.json

Fixes #591 
Can be checked with:
```
python -m armory run scenario_configs/librispeech_baseline_sincnet.json --check
```

Librispeech variable length input

---

armory/data/progress_percentage.py
armory/data/utils.py

Fix exception thrown by download_file_from_s3 to be KeyError when key is not in S3 bucket

Fix exception thrown by download_file_from_s3

---

armory/scenarios/video_ucf101_scenario.py

Fix UCF gpu memory leak

---

armory/__main__.py
armory/configuration.py
armory/docker/management.py
armory/paths.py
armory/scenarios/base.py
armory/utils/config_loading.py
armory/utils/config_schema.json
armory/utils/external_repo.py
docs/configuration_files.md

Also relaxes attack API requirements.

Custom pathing for evaluations

---

armory/scenarios/base.py

Make the number of train epochs 1 for poisoning scenario when --check is passed

---

armory/data/adversarial_datasets.py
armory/data/datasets.py
armory/scenarios/audio_classification.py
armory/scenarios/image_classification.py
armory/scenarios/video_ucf101_scenario.py

Disable shuffling of data during evaluation

---

armory/data/datasets.py
armory/data/utils.py

Fixes #665. Enables private dataset cache.

Allow registering of cached S3 checksum files

---

armory/scenarios/audio_classification.py
armory/scenarios/image_classification.py
armory/scenarios/video_ucf101_scenario.py

Confirm whether attack is targeted after loading

---

armory/art_experimental/attacks/fgm_binary_search.py
armory/scenarios/outputs.py

Create perturbation-accuracy plots. Not sure the best place to have an example (test) results json.

output plots

---

armory/scenarios/audio_classification.py
armory/scenarios/video_ucf101_scenario.py

enable use_label in audio and video scenarios 

---

armory/docker/management.py
armory/eval/evaluator.py

Honor --debug and colors in logging from inside the container

---

armory/environment.py
armory/eval/evaluator.py
armory/scenarios/base.py
armory/utils/external_repo.py

Warn user about amory version mismatch

---

armory/scenarios/audio_classification.py
armory/scenarios/image_classification.py
armory/scenarios/video_ucf101_scenario.py
armory/utils/config_loading.py
armory/utils/labels.py
scenario_configs/librispeech_baseline_sincnet_targeted.json
scenario_configs/resisc45_baseline_densenet121_targeted.json
scenario_configs/ucf101_baseline_pretrained_targeted.json

Fixes #688 
The updated configs demonstrate how to use targeted attacks with a round-robin scheme.

targeted attacks

---

armory/art_experimental/attacks/patch.py
armory/utils/config_loading.py
scenario_configs/resisc45_baseline_densenet121_adversarialpatch.json

Patch attacks rebase

---

armory/configuration.py

Enforce uniqueness of config directories

---

armory/utils/config_schema.json
armory/utils/metrics.py
scenario_configs/resisc45_baseline_densenet121_adversarialpatch.json

image circle patch area 

---

README.md
docs/dataset_licensing.md
docs/datasets.md
docs/index.md
mkdocs.yml

Add dataset licensing details

---

armory/__main__.py
armory/eval/evaluator.py
armory/scenarios/audio_classification.py
armory/scenarios/base.py
armory/scenarios/image_classification.py
armory/scenarios/poisoning_gtsrb_scenario.py
armory/scenarios/video_ucf101_scenario.py
armory/utils/metrics.py

Fixes #712. Also includes original command-line arguments in string passed to user in interactive mode.

Option to skip benign classification

---

scenario_configs/ucf101_baseline_adversarial.json

description and minor update

---

armory/data/datasets.py

Enable --check runs of video scenarios with finetuning

---

armory/scenarios/audio_classification.py
armory/scenarios/base.py
armory/scenarios/image_classification.py
armory/scenarios/poisoning_gtsrb_scenario.py
armory/scenarios/video_ucf101_scenario.py

set classifer inputs to be immutable

---

.github/workflows/ci_test.yml
STYLE.md
test-requirements.txt

Pin version of black

---

armory/__main__.py

Add a `--no-use-gpu` flag

---

armory/utils/config_schema.json

Allow multiple perturbation metrics

---

armory/__main__.py
armory/configuration.py

Allow configure to modify existing configuration

---

armory/data/cached_s3_checksums/so2sat.txt
armory/data/datasets.py

Create So2Sat dataset

---

armory/data/adversarial/apricot_dev.py
armory/data/adversarial_datasets.py
armory/data/cached_s3_checksums/apricot_dev.txt
armory/data/cached_s3_checksums/xview.txt
armory/data/datasets.py
armory/data/xview/xview.py
armory/utils/metrics.py
tests/test_pytorch/test_pytorch_models.py

Unify OD dataset keys and fix OD metrics to filter out adv patch id from groundtruth labels

---

armory/data/datasets.py

Load xView with PyTorch box format by default

---

scenario_configs/cifar10_baseline.json

ART's recently added verbose logging interferred destructively with Armory's logging
Closes #769

add verbose: False to cifar10_baseline.json

---

armory/utils/config_schema.json
armory/utils/metrics.py
scenario_configs/xview_frcnn.json

Add mAP metric for object detection

---

tests/test_pytorch/test_pytorch_models.py

Update xView test to use mAP

---

.github/workflows/release.yml
docker/build-dev.sh
docker/build.sh
docker/pytorch-deepspeech-dev/Dockerfile
docker/pytorch-deepspeech/Dockerfile

Push pytorch-deepspeech image to DockerHub on release

---

armory/docker/management.py
armory/eval/evaluator.py

don't throw spurious errors on container shutdown after armory exec or launch

---

README.md
docs/faqs.md
docs/getting_started.md
docs/metrics.md

Docs update (faq)

---

armory/data/adversarial_datasets.py
armory/data/datasets.py

Canonical preprocessing for adversarial datasets and non-scenario datasets

---

armory/data/datasets.py

variable y in xView (rebase)

---

scenario_configs/asr_deepspeech_baseline.json

This parameter has to be set to the max length of the test and dev dataset splits.

Update attack params

---

armory/data/utils.py

fast untarring when possible

---

armory/__main__.py
armory/utils/configuration.py
docs/command_line.md

Fixes #561
To test, try:
```
more scenario_configs/cifar10_baseline.json | armory run - --check
```
Should get a reasonable error message from:
```
echo "hi there" | armory run -
```

Piping from stdin

---

armory/baseline_models/pytorch/xview_frcnn.py
docs/metrics.md

xView model gpu fix

---

armory/utils/metrics.py
docs/metrics.md

iou warning logic

---

scenario_configs/ucf101_baseline_finetune.json
scenario_configs/ucf101_baseline_pretrained.json
scenario_configs/ucf101_baseline_pretrained_targeted.json

Fixes #862
Other scenarios appear appropriately scaled.

scaled epsilon

---

armory/baseline_models/pytorch/ucf101_mars.py
scenario_configs/ucf101_baseline_finetune.json
scenario_configs/ucf101_baseline_pretrained.json
scenario_configs/ucf101_baseline_pretrained_targeted.json

Optionally truncate very long videos in MARS model

---

docs/scenarios.md

Added baseline performance results for the xview scenario

Update xview results

---

armory/baseline_models/keras/cifar.py
armory/baseline_models/keras/densenet121_resisc45.py
armory/baseline_models/keras/inception_resnet_v2.py
armory/baseline_models/keras/micronnet_gtsrb.py
armory/baseline_models/keras/mnist.py
armory/baseline_models/keras/resnet50.py
armory/baseline_models/keras/so2sat.py
armory/baseline_models/pytorch/cifar.py
armory/baseline_models/pytorch/deep_speech.py
armory/baseline_models/pytorch/mnist.py
armory/baseline_models/pytorch/resnet50.py
armory/baseline_models/pytorch/sincnet.py
armory/baseline_models/pytorch/ucf101_mars.py
armory/baseline_models/pytorch/xview_frcnn.py

Add type annotations to baseline models. Still adding docstrings, but want to run CI testing on the type annotations.

Add type annotations to baseline models

---

docker/build-dev.sh
docker/build.sh
docker/pytorch-deepspeech-dev/Dockerfile
docker/pytorch-deepspeech/Dockerfile

Fixes #787
Fixes #874
I needed to revert pytorch to 1.4 and torchaudio to 0.4 (this is to fix the NaNs issue).
Also simplified the builds a bit for pytorch-deepspeech.
Rebase of #868 that moves ART to the end.

Deepspeech nan rebase

---

armory/scenarios/base.py

Return non-zero exit code if validate-config fails

---

armory/utils/evaluation.py

Adding patch_method for overriding model methods

---

armory/eval/evaluator.py

Fix TORCH_HOME in --no-docker mode

---

armory/eval/evaluator.py

Update HOME directory in container for jupyter to work in non-root mode

---

armory/data/cached_s3_checksums/librispeech_full.txt
armory/data/datasets.py
armory/data/librispeech/librispeech_full.py
armory/data/url_checksums/librispeech_full.txt
docs/datasets.md

Adds librispeech_full dataset with all splits

Librispeech_full

---

armory/data/adversarial_datasets.py
armory/data/datasets.py
armory/scenarios/audio_asr.py
armory/scenarios/audio_classification.py
armory/scenarios/base.py
armory/scenarios/image_classification.py
armory/scenarios/video_ucf101_scenario.py
armory/utils/config_schema.json
armory/utils/export.py
docs/scenarios.md

Save adversarial examples for listening/viewing

---

armory/data/utils.py
armory/utils/config_loading.py

auto-expand tarballs submitted as weights files

---

armory/data/cached_s3_checksums/ucf101_clean.txt
armory/data/datasets.py
armory/data/ucf101/ucf101_clean.py
armory/data/url_checksums/ucf101_clean.txt
docs/datasets.md

Fixes #791 
This still needs to be built and use the s3 cache. Building on a small portion, it works well, though.

ucf101 clean

---

armory/art_experimental/attacks/pgd_patch.py
armory/scenarios/multimodal_so2sat_scenario.py

Fixes #961 
I changed the `channels` argument back to the binary `mask` argument to allow compatibility with other attack types.

Fixes so2sat mask bug

---

tests/test_tf1/test_tf1_models.py

apricot skip

---

armory/baseline_models/pytorch/micronnet_gtsrb.py
tests/test_pytorch/test_pytorch_models.py

Micronnet model using pytorch sequential api

---

armory/baseline_models/pytorch/cifar.py
armory/baseline_models/pytorch/resnet50.py
armory/baseline_models/pytorch/ucf101_mars.py

channels_first pytorch models

---

docker/build.sh

Added command echoes and ensured that dev building also locally tagged the latest. (Otherwise, this needs to be done manually by the user.)

Build tag script

---

armory/data/cached_s3_checksums/cifar100.txt
armory/data/datasets.py
tests/test_docker/test_dataset.py

CIFAR-100 dataset for use with bullseye polytope transfer attack.

CIFAR-100 dataset

---

armory/utils/external_repo.py

external repo fix

---

scenario_configs/ucf101_baseline_pretrained_pgd_patch.json

UCF config bug

---

armory/data/integrate_tfds.py

Bugfix in the TFDS integration script - now correctly creates a tarfile with the directory structure expected by armory.

Bugfix: Integrate TFDS script

---

host-requirements.txt

Describes self-consistent dependencies and notes where special, non-pip actions need to be done according to local configuration.

improved host requirements definition for no-docker installations

---

armory/art_experimental/attacks/kenansville_dft.py

Benchmark on a 3sec clip shows 40x+ speedup. More than fast enough to train models directly on attacked audio samples
Resolves #1103
Was tested outside of Armory.

Optimize Kenansville attack and fixes bug

---

armory/utils/config_schema.json
armory/utils/metrics.py
tests/test_docker/test_metrics.py

Adds the ability to measure whether a model is abstaining

abstain metric

---

armory/scenarios/poisoning_gtsrb_clbd.py
armory/scenarios/poisoning_gtsrb_scenario.py
armory/scenarios/poisoning_resisc10_scenario.py
armory/utils/metrics.py

Needs to be more fully tested before merging.

Dev 0.13.5 poison

---

README.md

Signed-off-by: Beat Buesser <beat.buesser@ie.ibm.com>

Update README on ART

---

armory/data/cached_s3_checksums/resisc10_poison.txt
armory/data/datasets.py
armory/data/resisc10/resisc10_poison.py
armory/data/url_checksums/resisc10_poison.txt
tests/test_docker/test_dataset.py

Link to new dataset sent separately.

updating RESISC-10 from 64x64 images to 256x256 images

---

armory/scenarios/scenario.py
armory/utils/config_loading.py
scenario_configs/carla_obj_det_dpatch_undefended.json
scenario_configs/carla_obj_det_multimodal_dpatch_undefended.json

Standard items are removed from dataset_config and everything else is assumed to be a kwarg for the dataset loading function.

Refactor dataset config loading

---

.github/workflows/ci_test.yml

Update ci python

---

armory/data/adversarial/carla_video_tracking_test.py

moving cv2 import inside method

---

.github/workflows/ci_test.yml

The changes in 36edbf3 were applied to master but not develop

merge master into develop

---

armory/utils/metrics.py

Fixes [1250](https://github.com/twosixlabs/armory/issues/1250)

compute carla_od_AP_per_class after all predictions have been obtained

---

armory/scenarios/carla_object_detection.py
armory/scenarios/carla_video_tracking.py
armory/scenarios/scenario.py
armory/utils/export.py

Allows exporting of bounding boxes for object detection scenarios

Export bounding boxes for carla image and video

---

docker/tf1/Dockerfile
docker/tf2/Dockerfile

I think this should solve the tf2 issue (for now).

fix tf2 ci test

---

docker/pytorch-deepspeech/Dockerfile
docker/pytorch/Dockerfile
scenario_configs/librispeech_asr_imperceptible_defended.json
scenario_configs/librispeech_asr_imperceptible_undefended.json
scenario_configs/librispeech_asr_kenansville_defended.json
scenario_configs/librispeech_asr_kenansville_undefended.json
scenario_configs/librispeech_asr_pgd_defended.json
scenario_configs/librispeech_asr_pgd_multipath_channel_defended.json
scenario_configs/librispeech_asr_pgd_multipath_channel_undefended.json
scenario_configs/librispeech_asr_pgd_undefended.json
scenario_configs/librispeech_asr_snr_undefended.json

Simple docker pytorch deepspeech

---

armory/baseline_models/keras/cifar.py
armory/baseline_models/keras/densenet121_resisc45.py
armory/baseline_models/keras/inception_resnet_v2.py
armory/baseline_models/keras/micronnet_gtsrb.py
armory/baseline_models/keras/mnist.py
armory/baseline_models/keras/resnet50.py
armory/baseline_models/keras/so2sat.py
armory/baseline_models/tf_graph/mnist.py
armory/baseline_models/tf_graph/mscoco_frcnn.py
scenario_configs/apricot_frcnn.json
scenario_configs/apricot_frcnn_defended.json
scenario_configs/dapricot_frcnn_masked_pgd.json
scenario_configs/gtsrb_scenario_baseline.json
scenario_configs/gtsrb_scenario_clbd.json
scenario_configs/gtsrb_scenario_clbd_bullethole.json
scenario_configs/gtsrb_scenario_clbd_defended.json
scenario_configs/gtsrb_scenario_poison.json
scenario_configs/mnist_baseline.json
scenario_configs/resisc45_baseline_densenet121.json
scenario_configs/resisc45_baseline_densenet121_cascade.json
scenario_configs/resisc45_baseline_densenet121_finetune.json
scenario_configs/resisc45_baseline_densenet121_patch.json
scenario_configs/resisc45_baseline_densenet121_sweep_eps.json
scenario_configs/resisc45_baseline_densenet121_targeted.json
scenario_configs/so2sat_eo_masked_pgd_defended.json
scenario_configs/so2sat_eo_masked_pgd_undefended.json
scenario_configs/so2sat_sar_masked_pgd_defended.json
scenario_configs/so2sat_sar_masked_pgd_undefended.json

Partially does #1289
This is the first step in moving away from tf1 - remove from configs and enable compatibility in tf2.

TF1 deprecation

---

armory/scenarios/__init__.py

remove unused import statement

---

armory/logs.py

Fixes #1328
Enables `backtrace` and `diagnose` options to loguru which trigger when there is an active exception. This makes log.exception work like the standard logger.exception.
The `diagnose` option uses loguru's embedded [better-exceptions](https://github.com/Qix-/better-exceptions) detailed and colorful backtraces. The detail might be excessive and can be set to False but let's see.

enable log.exception backtrace

---

armory/scenarios/scenario.py

add checks for evaluate_current

---

armory/data/datasets.py
armory/data/pytorch_loader.py

update torch loader

---

armory/docker/images.py

TF1 deprecation error

---

armory/scenarios/carla_object_detection.py

Fixes #1354
Fixes #1343 
Also fixes an unnoticed bug where if `"record_metric_per_sample": true` in config, it wouldn't apply to the CARLA-specific added metrics.

update scenario to properly override Scenario

---

scenario_configs/gtsrb_scenario_baseline.json
scenario_configs/gtsrb_scenario_baseline_pytorch.json
scenario_configs/gtsrb_scenario_clbd.json
scenario_configs/gtsrb_scenario_clbd_bullethole.json
scenario_configs/gtsrb_scenario_clbd_defended.json
scenario_configs/resisc10_poison_dlbd.json

Should have been reformatted already.

update format of poisoning

---

armory/scenarios/poison.py
armory/utils/poisoning.py

Writes additional info in results json for poisoning scenario, such as f1 score, true negative/positive rate, accuracy per class, etc.
Addresses #1379 and #1355

additional poison results output

---

armory/scenarios/carla_object_detection.py

CARLA --skip-attack bug fix

---

armory/data/cached_s3_checksums/carla_obj_det_train.txt
armory/data/carla_object_detection/carla_obj_det_train.py
armory/data/datasets.py
armory/data/url_checksums/carla_obj_det_train.txt
docs/datasets.md
tests/end_to_end/test_e2e_datasets.py

Dataset url to be sent separately

Updated CARLA Object Detection Training Data

---

armory/utils/config_schema.json
armory/utils/metrics.py
scenario_configs/carla_video_tracking_goturn_advtextures_defended.json
scenario_configs/carla_video_tracking_goturn_advtextures_undefended.json
tests/unit/test_metrics.py

adding mean success rate for video tracking

---

armory/data/adversarial/carla_video_tracking_dev.py
armory/data/adversarial_datasets.py
armory/data/cached_s3_checksums/carla_video_tracking_dev.txt
armory/data/url_checksums/carla_video_tracking_dev.txt
tests/end_to_end/test_e2e_datasets.py

Link to dataset sent separately

For Issue #1371 - Eval5 carla video tracking dev dataset

---

docs/docker.md

Fix #1321 - Documentation for using cuda 10.2

---

armory/data/adversarial_datasets.py

fix carla test set preprocessing

---

armory/scenarios/multimodal_so2sat_scenario.py

fix so2sat metrics

---

armory/data/datasets.py
armory/scenarios/poisoning_gtsrb_scenario.py
scenario_configs/eval5/poisoning/gtsrb_witches_brew.json

For #1459 
Moves gtsrb preprocessing function to dataset.py instead of the gtsrb scenario.
This allows other scenarios like witches' brew to use gtsrb.

Gtsrb preprocessing

---

notebooks/running_armory_scenarios_interactively.ipynb
test-requirements.txt
tests/jupyter_manual_test.ipynb

add black[jupyter]

---

armory/baseline_models/pytorch/ucf101_mars.py

fix ucf101 fine-tune training

---

armory/instrument/instrument.py
tests/unit/test_instrument.py

add hub disconnect_meter() method

---

armory-base-requirements.txt
docker/Dockerfile-pytorch
docker/Dockerfile-pytorch-deepspeech
docker/Dockerfile-tf2
host-requirements.txt
scenario_configs/eval1-4/asr_librispeech/librispeech_asr_imperceptible_defended.json
scenario_configs/eval1-4/resisc45/resisc45_baseline_densenet121_cascade.json

Fixes #1523
This may fix
#1465 
#1467 - I'll upload new scenario config:
`scenario_configs/eval1-4/resisc45/resisc45_baseline_densenet121_cascade.json`
#1472 
But that needs to be tested.
The fix for #1468 is slated for a later version of ART.

update to art 1.10.2

---

mkdocs.yml

update mkdoc structure

---

armory/scenarios/poisoning_witches_brew.py
docs/poisoning.md

Attack success for witches brew

---

armory/metrics/task.py

allow total_wer() to take in list or np array

---

scenario_configs/eval5/carla_video_tracking/carla_video_tracking_goturn_advtextures_defended.json

update defense name in carla_video_tracking_goturn_advtextures_defended.json config

---

armory/art_experimental/attacks/gradient_matching.py
armory/scenarios/poisoning_witches_brew.py

Taesung confirmed that the classifier passed to the attack should be already trained.

Witches brew proxy model fix

---

.github/workflows/release.yml
docker/build.py

This is a cherry-pick of the #1535 patch to develop.

Fix release CI job for 0.15.2 branch

---

.github/workflows/release.yml
docker/build.py

Bring-1535-ci-fix-to-master-take2

---

armory/data/adversarial/carla_obj_det_test.py
armory/data/adversarial/carla_video_tracking_test.py
armory/data/adversarial_datasets.py
armory/data/cached_s3_checksums/carla_obj_det_test.txt
armory/data/cached_s3_checksums/carla_video_tracking_test.txt
armory/data/url_checksums/carla_obj_det_test.txt
armory/data/url_checksums/carla_video_tracking_test.txt
docs/adversarial_datasets.md
tests/end_to_end/test_e2e_datasets.py

includes video tracking test 2.0.0 and object detection test 2.0.0, rebased from #1575 and #1573

Eval5 carla test sets

---

armory/baseline_models/pytorch/resnet18.py

We see some attacks perform differently on a model trained on different optimizers. To test that, I want to add a ResNet-18 model optimized with SGD.

Adding a ResNet-18 model optimized with SGD.

---

docs/scenarios.md

Updated Scenario.md with Eval 5 CARLA Test Results

---

.dockerignore
armory/docker/images.py
docker/Dockerfile-base
docker/Dockerfile-pytorch
docker/build.py
environment.yml

1. restore docs and datafiles to docker build
2. validate version hash syntax
3. calculate fallback version if different.
4. use mamba instead of conda
5. add mamba environment.yml

Build update

---

scenario_configs/eval6/carla_mot/carla_mot_adversarialpatch_undefended.json
scenario_configs/eval6/carla_mot/carla_mot_dpatch_defended.json
scenario_configs/eval6/carla_mot/carla_mot_dpatch_undefended.json

These are example configs but may change depending on actual integration.

Eval 6 - CARLA MOT Example Configs

---

armory/data/datasets.py

update imagenette version

---

armory/baseline_models/pytorch/hubert_asr_large.py
scenario_configs/eval6/asr_librispeech/hubert_untargeted_snr_pgd.json

This will replace the Deep Speech 2 model with Hubert. It is more modern, better performing, and just uses basic `torchaudio`.

Hubert ASR - replacement for deep speech without the dependencies

---

docs/adversarial_datasets.md
tests/end_to_end/test_e2e_datasets.py

Carla mot dataset

---

armory/art_experimental/attacks/carla_obj_det_adversarial_patch.py
armory/art_experimental/attacks/carla_obj_det_patch.py
armory/art_experimental/attacks/carla_obj_det_utils.py

Updated CARLA object detection attacks to work with linear depth images.

Eval 6 - CARLA Object Detection Depth Attack Update

---

armory/metrics/task.py
armory/scenarios/carla_mot.py

This does *not* get things into the meter format. However, it should now produce the correct set of results to the output dict and print the correct info to screen.

WIP: MOT: update task results

---

.github/workflows/release.yml

add release tag to pipeline

---

docs/no_docker_mode.md

document hyrda-lightning install for no-docker users

---

armory/__main__.py
armory/docker/images.py

use armory.__version__ as the standard access

---

README.md

pip 21 issue note

---

armory/scenarios/carla_video_tracking.py

change output dir of CARLA video tracking exporter

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/actions/evaluations_environment_setup/action.yml
.github/workflows/1-scan-lint-build.yml
.github/workflows/2-test-stand-alone.yml
.github/workflows/3-test-docker.yml
.github/workflows/ci_test.yml
.github/workflows/end2end_cron.yml
.github/workflows/release.yml
.github/workflows/scenario-runner.yml
.github/workflows/tests/scenario-evaluation-config.json
armory/__main__.py
armory/docker/management.py
tests/conftest.py
tests/end_to_end/test_e2e_scenarios.py

Closes: #1700 #1148 #1610 
Adds scenario runner to e2e CI job

Add scenario runner to CI

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/actions/evaluations_environment_setup/action.yml
.github/workflows/1-scan-lint-build.yml
.github/workflows/2-test-stand-alone.yml
.github/workflows/3-test-docker.yml
.github/workflows/ci_test.yml
.github/workflows/end2end_cron.yml
.github/workflows/release.yml
.github/workflows/scenario-runner.yml
.github/workflows/tests/scenario-evaluation-config.json
armory/__main__.py
armory/docker/management.py
tests/conftest.py
tests/end_to_end/test_e2e_scenarios.py

Adds a workflow to run scenarios for a given eval period to 0.16.1 release 
- In `armory/docker/management.py` replace decode errors from armory output; there are ANSI line-drawing characters which are not convertable
- In `armory/__main__.py` function `run` now returns a status code to `main` instead of `sys.exit(code)`

Add workflow to run scenarios

---

.github/workflows/scenario-runner.yml

- Adds the `eval6` directory
- Fixes path error

Adds eval 6 to the scenario runner

---

armory/scenarios/scenario.py
armory/utils/config_loading.py

Modify how armory handles targeted attacks

---

armory/art_experimental/attacks/carla_obj_det_adversarial_patch.py
armory/art_experimental/attacks/carla_obj_det_patch.py
scenario_configs/eval5/carla_object_detection/carla_obj_det_multimodal_adversarialpatch_defended.json
scenario_configs/eval5/carla_object_detection/carla_obj_det_multimodal_adversarialpatch_undefended.json
scenario_configs/eval5/carla_object_detection/carla_obj_det_multimodal_dpatch_defended.json
scenario_configs/eval5/carla_object_detection/carla_obj_det_multimodal_dpatch_undefended.json

make carla attacks backwards compatible

---

tools/pre-commit.sh

Fix pre-commit hooks

---

tools/pre-commit.sh

Minor thing that fell out of the rewrite.

don't double print black

---

armory/logs.py

Fixes #1743
@mwartell I'd like you to look at what I'm doing here, since you understand what `loguru` is doing behind the scenes.

enable configurable tensorflow c++ logging

---

docs/style.md

update bash link documentation

---

armory/art_experimental/attacks/sweep.py

resisc sweep bug

---

scenario_configs/eval1-4/xview/xview_frcnn_sweep_patch_size.json

Fix xview sweep bug

---

armory/scenarios/scenario.py
docs/command_line.md

adding attack kwargs to set to 1 when --check

---

armory/baseline_models/tf_graph/audio_resnet50.py

Activation bug resnet50

---

armory/data/datasets.py
armory/scenarios/poison.py
docs/poisoning.md
scenario_configs/eval6/poisoning/audio_dlbd/audio_p01_undefended.json
tests/unit/test_datasets.py

Fixes #1761
To test, you can set `fit_generator` to `true` in the `scenario` `kwargs` of the `audio_p01_undefended.json` config.

Oom error poisoning

---

armory/metrics/poisoning.py
armory/scenarios/poison.py
docs/poisoning.md

Another poisoning use of batched predictions

---

.github/workflows/scenario-runner.yml
tests/end_to_end/test_e2e_scenarios.py

Update Scenario Runner CI Job

---

armory/datasets/config_load.py
armory/datasets/generator.py
armory/scenarios/scenario.py

This one will just modify the ART wrapper piece.

update art generator wrapping

---

armory/metrics/statistical.py
armory/metrics/task.py
tests/unit/test_perturbation_metrics.py

Addressing CI failures from #1832 resulting from jump to numpy 1.24

fix numpy ci failures

---

armory/datasets/cached_datasets.json

the config is already updated, and preprocessing has already been added. So this is just a simple addition to the json

updating cached_datasets.json with cifar10

---

armory/instrument/export.py

Closes #1824, see link for description of the bug and how to reproduce

updating VideoTrackingExporter class for new label format

---

docs/baseline_results/carla_od_results.md

Addressing https://github.com/twosixlabs/armory/issues/1852

---

.github/workflows/self-hosted.yml

This was added in one branch and not present in another. We want this file present.

Fix 0.16.2 merge conflict

---

armory/instrument/export.py

round to nearest int when exporting, rather than rounding down

---

armory/instrument/export.py

fix video tracking export bug

---

armory/art_experimental/attacks/carla_obj_det_patch.py

Fix bug to allow correct custom initialization of RGB channels of a multimodal input.

Multimodal Robust DPatch Bug Fix

---

armory/art_experimental/attacks/carla_obj_det_patch.py
armory/scenarios/poisoning_sleeper_agent.py

A single letter bugfix #1866 already approved by @lcadalzo on merge to develop.  This PR exists because `master` is protected against merges.

armory v0.16.4 release

---

armory/instrument/export.py

MOT export bug: removing decrement of index to avoid KeyError

---

pyproject.toml

advance art to 1.14.0

---

pyproject.toml

Art 1.14.1 has some important bug fixes for OD poisoning

upgrade art to 1.14.1

---

armory/metrics/__init__.py

Reverts twosixlabs/armory#1900

Revert "Adding import error message to reported error"

---

docs/baseline_results/carla_mot_results.md
scenario_configs/eval7/carla_mot/carla_mot_adversarialpatch_undefended.json
scenario_configs/eval7/carla_mot/carla_mot_dpatch_defended.json
scenario_configs/eval7/carla_mot/carla_mot_dpatch_undefended.json

add example mot configs for eval7

Carla MOT eval7 configs

---

tools/run_scenario_configs.sh

this was causing new git clones to be dirty immediately after cloning. soooo weird! (msw & cjw)

removed tools/run_scenario_configs.sh

---

armory/art_experimental/attacks/poison_loader_audio.py

removing code that was merged into ART, to fulfill #1931

Clean up audio poison loader

---

notebooks/running_armory_scenarios_interactively.ipynb

Updates cells relevant to Google Colab in order to handle numpy version mismatch. See, https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility

Update Google Colab notebook

---

.github/workflows/3-test-docker.yml
.github/workflows/release.yml
armory/docker/images.py
docker/Dockerfile-yolo
docker/build.py
docs/docker.md
docs/poisoning_object_detection.md
notebooks/running_armory_scenarios_interactively.ipynb
pyproject.toml
scenario_configs/eval7/poisoning/obj_det_dlbd_GMA.json
scenario_configs/eval7/poisoning/obj_det_dlbd_ODA.json
scenario_configs/eval7/poisoning/obj_det_dlbd_OGA.json
scenario_configs/eval7/poisoning/obj_det_dlbd_RMA.json
tools/run_scenario_configs.sh

This PR adds a docker image for YOLO experiments. See Issue #1936

1936 create yolo docker image

---

notebooks/running_armory_scenarios_interactively.ipynb

Adds note on how to manually restart the runtime.
Fixes pprint import.

Google Colab fixes

---

armory/art_experimental/attacks/carla_obj_det_adversarial_patch.py
armory/art_experimental/attacks/carla_obj_det_patch.py
armory/scenarios/carla_object_detection.py
armory/utils/labels.py
scenario_configs/eval7/carla_overhead_object_detection/carla_obj_det_adversarialpatch_targeted_undefended.json
scenario_configs/eval7/carla_overhead_object_detection/carla_obj_det_multimodal_adversarialpatch_targeted_undefended.json

This PR updates two items:
1. The depth patch region now matches the RGB patch region
2. Added a targeted attack option for the CARLA object detection evasion scenarios. This includes changes to the attack code, new targeted attack configs, and a random target generator.

Carla attack update

---

tests/end_to_end/test_e2e_datasets.py

Use the new split names in the Carla Overhead OD dataset unit test ("test_hallucination" and "test_dataset")

Update split names in Carla dataset test

---

armory/scenarios/poison.py

update np.bool reference

---

docs/command_line.md
docs/utils.md

`armory utils` documentation
