armory/baseline_models/pytorch/imagenet.py, armory/data/datasets.py, armory/docker/management.py, armory/eval/evaluator.py, armory/eval_scripts/carlini_wagner_attack_targeted.py, armory/eval_scripts/fgm_attack.py, armory/eval_scripts/fgm_attack_binary_search.py, armory/eval_scripts/poisoning_attack_backdoor.py, armory/eval_scripts/transfer_attack.py, armory/paths.py, armory/utils/external_repo.py, tests/test_dataset.py, tests/test_external_repo.py
We previously removed this strategy since we considered mounting the host's pip installed armory in the container (which could require root to use/modify). 
Since we've since installed the armory package within the container this is no longer needed. Saving files as root onto the user's host caused a number of issues and is a pretty poor practice.
=> Mount volumes as host user

armory/__init__.py, armory/art_experimental/__init__.py, armory/art_experimental/attacks/poisoning_attack_backdoor.py, armory/data/__init__.py, armory/docker/__init__.py, armory/eval/__init__.py, armory/utils/__init__.py
Enables for example:
```
import armory
armory.art_experimental.attacks.FGMBinarySearch
```
=> Fix import structure for top level imports

armory/__main__.py
Command line usage (after pip install):
```
$ armory --version
armory 0.4.1
```
```
$ armory -v
armory 0.4.1
```
```
$ armory --help
armory <command>
ARMORY Adversarial Robustness Evaluation Test Bed
https://github.com/twosixlabs/armory
Commands:
run - run armory from config file
download-all-data - download all datasets and model weights used by armory
clean - download new and remove all old armory docker images
-v, --version - get current armory version
Run 'armory <command> --help' for more information on a command.
```
fixes #193
=> command line version

.github/workflows/release.yml
Closes #189 
Per discussion pre-release trigger doesn't really accomplish what we want to do here. API trigger for builds and then we can release will work.
Example test:
https://github.com/armory-twosix/testing-actions/blob/master/.github/workflows/blank.yml
https://github.com/armory-twosix/testing-actions/runs/469965239?check_suite_focus=true
=> Update release to trigger from API

armory/baseline_models/keras/keras_inception_resnet_v2.py, tests/test_dataset.py
Update transfer attack to resize input dimensions and added test (Issue #200). The transfer attack leads to a drop in accuracy from 75.5% to 71.8%, which suggests that the impact on the adversarial data is within tolerance.
=> Update transfer attack to resize and add test

armory/__main__.py, armory/docker/images.py, docker/build-dev-minimal.sh, docker/build-dev.sh, docker/build.sh
fixes #258 
1) It still uses distutils to check for strict versioning, but uses pkg_resources for comparisons.
This merge also does two other things:
2) uses --force-rm when creating docker images to remove intermediate containers on failed builds
3) updates armory clean to handle "-dev" versions. (When using clean on "-dev", it only removes old "-dev" images.)
=> Docker clean

armory/__main__.py, armory/eval/evaluator.py
part of #264 - this creates two main commands:
`exec`, which allows you to run an arbitrary bash command inside a just launched container.
This is more general than a `test` command, and can be used with pytest. The remaining piece for #264 is to get the exit code from pytest to get passed to the main function, so that it can it turn send it to the CI runner.
`launch`, which is a convenience command similar to `run` that enables launching a docker image in armory without a specific evaluation config.
=> Docker launch test

armory/data/README.md
Will add more info on the ArmoryDataSet generator after we move to ART1.2
Also you'll notice we need to work on our standardization of data types. Is there any reason we can't standardize on x = float32 ; y =int64 ?
=> Update dataset docs

armory/docker/management.py, armory/docker/volumes_util.py, armory/eval/evaluator.py, armory/paths.py, armory/utils/external_repo.py, tests/test_host/test_external_repo.py
Should enable multiple docker containers to run simultaneously without impacting each others`tmp` and `output` directories. Collisions can still happen on `datasets` and `models`, but those are expected/desired.
fixes #178
=> Multiple container

armory/data/datasets.py, tests/test_docker/test_dataset.py
This enables datasets with variable size inputs (ucf101, librispeech, imagenette, german_traffic_sign, digits) to have batch_size > 1. This is handled differently for datasets backed by numpy arrays (in memory) and for those backed by TFDS.
The output batches are 1D np arrays of dtype object. In order to work with most systems, these will need to be modified by a preprocessing function prior to training on most models. Since this could involve a wide variety of functionality (clipping, zero-padding, masking), I think those should be handled more directly by users.
=> update datasets for variable length input

tests/evals/resisc45_scenario.py
Without this fix, the benign/adversarial accuracies for Evaluation Results written to <output_dir>/evaluation-results.json can be >100%
=> fix accuracy calculation for example resisc scenario

.github/workflows/ci_test.yml, armory/utils/external_repo.py, tests/test_host/test_external_repo.py
Need to authenticate our API calls because of shared IP adressed on github action VMs. Unable to use github secrets since PRs from forks do not have access to them. 
The token in this PR is read_only repo access to public repositories.
=> Authenticate CI api calls

armory/data/datasets.py, docker/Dockerfile, tests/evals/fgm_attack.py, tests/evals/resisc45_scenario.py, tests/test_docker/test_dataset.py, tests/test_pytorch/test_pytorch_models.py, tests/test_tf1/test_keras_models.py
* No longer uses epochs*examples as `size` since 1.2 now properly uses epochs in `fit_generator`:
https://github.com/IBM/adversarial-robustness-toolbox/pull/325/files#diff-d8fef06604d63d41409534325ce29c6f
This causes an issue with using testset data generators with multiple epochs loaded. The last batch of the first epoch will take from the next epoch if they are not divisible. I think it's cleaner to just load the testsets individually with epoch=1.
=> Utilize ART 1.2

armory/data/utils.py
Currently, if the cache file exists but is incorrect, this will be caught after the "download" portion in verification, which will fail. This will then fall back to the full dataset processing, like so:
```
>>> d = datasets.librispeech_dev_clean("train", 1, 1)
2020-03-26 19:59:30 5315d24e3726 armory.data.utils[14] INFO Dataset already downloaded.
2020-03-26 19:59:30 5315d24e3726 armory.data.utils[14] WARNING Cached file download failed. Falling back to processing data...
...
```
With this change, it will verify any existing cache file, delete it if corrupted, re-download from cache, re-verify, and only go to processing if that also fails. Here is what a typical run would look like:
```
>>> d = datasets.librispeech_dev_clean("train", 1, 1)
2020-03-26 20:06:08 5315d24e3726 …
```
=> Verify download if cache .tar.gz file exists

armory/paths.py
I came across `@functools.lru_cache` as a function decorator useful for caching / running a function only once. This is what I had handrolled here before, but I think it's a lot cleaner to use the built-in version.
=> Path caching

README.md, armory/data/utils.py
Exact details of the bug are unclear (could not replicate locally), but the boto3 call seems to be intermittently creating segmentation faults during CI testing. Below are two example failing CI tests:
https://github.com/twosixlabs/armory/runs/540390645?check_suite_focus=true
https://github.com/twosixlabs/armory/runs/540179652?check_suite_focus=true
=> Use curl with download_verify_dataset_cache

armory/data/datasets.py, tests/test_docker/test_dataset.py
Enable iteration (and enumeration) of ArmoryDataGenerator.
It's definitely counterintuitive to have a generator that you can't directly iterate on. This small change enables that. It also enables syntactic sugar which might be nice for scenarios. Thus:
```python
cnt = 0                                                                              
for _ in range(test_data_generator.batches_per_epoch):                               
x, y = test_data_generator.get_batch()                                           
test_x_adv = attack.generate(x=x)                                                
predictions = classifier.predict(test_x_adv)                                     
adversarial_accuracy += np.sum(np.argmax(predictions, axis=1) == y) / len(y)     
cnt += 1
adversarial_accuracy = …
```
=> ArmoryDataGenerator implements iterator interface

.github/workflows/ci_test.yml, armory/baseline_models/pytorch/cifar.py, armory/baseline_models/pytorch/mnist.py, armory/baseline_models/pytorch/resnet50.py, tests/configs/pytorch/fgm_attack_test.json
Closes #342 
Better than having to parse a GPU config, if it's available then it'll be used. Same strategy our TF models use.
=> Utilize GPU for pytorch models if available

armory/eval/evaluator.py
I keep running a command like this:
```armory run armory/scenarios/cifar10.py```
This, of course, results in a JSON decoding error, and it takes a second to recall why. So, I've added some logging to point users to imputting json.
=> some logging

armory/utils/metrics.py
Also, makes categorical_accuracy return 0/1.
numpy.linalg.norm only works on 1D and 2D matrices, which is why I'm not just calling it directly.
=> update metrics to use np

armory/eval/evaluator.py
Since there is no longer "evaluation" in configs, this part of the logging was not displaying anyting.
=> minor logging bug due to config change

docs/docker.md
Fixes #192 
Instead of doing a hacky workaround for this bug, since it's not a functional issue, I have documented it in `docs/docker.md`. That should be sufficient, I think, to close it.
=> updated docker docs for interactive usage

armory/data/datasets.py, armory/utils/config_loading.py, armory/utils/config_schema.json, docs/configuration_files.md, docs/datasets.md, scenario_configs/cifar10_baseline.json, scenario_configs/cifar10_defended_example.json, scenario_configs/gtsrb_scenario_baseline.json, scenario_configs/librispeech_baseline_sincnet.json, scenario_configs/mnist_baseline.json, scenario_configs/resisc45_baseline_densenet121.json, scenario_configs/resisc45_baseline_densenet121_finetune.json, scenario_configs/ucf101_baseline_finetune.json, scenario_configs/ucf101_baseline_pretrained.json, tests/scenarios/broken/invalid_dataset_framework.json, tests/scenarios/pytorch/image_classification.json, tests/scenarios/pytorch/image_classification_pretrained.json, tests/scenarios/tf1/image_classification.json, tests/scenarios/tf1/image_classification_pretrained.json, tests/test_docker/test_dataset.py, tests/test_host/test_config_verification.py, tests/test_pytorch/test_framework_dataset.py, tests/test_tf1/test_framework_dataset.py
Closes #452 
Wanted to discuss the implementation a little bit before finalizing. It's a bit tricker than expected since in TF the Dataset we're working with prior to `as_numpy` is a tf.data.Dataset which is not iterable since it's used in graph execution (This applies to TF1 and TF2). That means we can't pass it to ArmoryDataGenerator and it will not have a `get_batch` method for ART to use. It may still be useful for users to have this type of dataset be returned for their own training etc. but it doesn't fit as nicely in the framework as we had hoped. 
We can coerce the dataset into an iterable by executing the session, but not sure if that's preferable. Similar to how it's done for ART:
https://github.com/IBM/adversarial-robustness-toolbox/blob/c3434e6e9406df4a25d91dd7c746beb019be2bd2/ …
=> Enable tf.data.Dataset return

.github/workflows/release.yml, armory/__init__.py, docker/build-dev.sh, docker/build.sh
Fixes #476 
There are three things to resolve before removing WIP status:
1) How do we test this?
2) Is the `__previous_docker_version__` (or alternatively, `__previous_version__`) what we want to use to pull older docker containers? We could use the "latest" tag, but that may make it harder to test things. (And I don't know if we want performers trying to pull "latest".)
3) (minor) For our first build, we'll need a previous version of the `armory` container so that it doesn't error when it tries to pull one.
However, I think review before resolving these would be helpful.
=> Updated docker release process

armory/eval/evaluator.py
The temp directories are created through armory.paths()
=> Remove unnecessary tmp dir creation

armory/scenarios/base.py
fixes #517
Currently, we save the timestamp in the filename, but not in the json output. Saving it to the json output dict as well will make it easier to transfer all the data to a database or return to a client.
=> add timestamp to output dict

armory/__main__.py, armory/baseline_models/keras/resnet50.py, armory/configuration.py, armory/data/datasets.py, armory/data/model_weights.py, armory/data/resisc45/resisc45_dataset_partition.py, armory/data/utils.py, armory/docker/management.py, armory/eval/evaluator.py, armory/paths.py, armory/scenarios/base.py, armory/utils/external_repo.py, docs/docker.md, tests/conftest.py, tests/test_docker/test_dataset.py, tests/test_docker/test_weight_download.py, tests/test_host/test_external_repo.py, tests/test_pytorch/test_framework_dataset.py, tests/test_pytorch/test_pytorch_models.py, tests/test_tf1/test_framework_dataset.py, tests/test_tf1/test_keras_models.py
* Moves global configuration into its own module instead of handled within path objects
* Removes verify_ssl from paths
* Creates new access point `runtime_paths` instead of overloading docker()
* Uses standard python classes / inheritance to hold the path information
* Fixes ResNet50 weights loading to utilize shared utility.
=> Refactor path referencing

armory/__main__.py, armory/configuration.py, armory/eval/evaluator.py, docs/docker.md
Primary changes:
* Updated usage of `print` and `logger`, so that the former only happens either before the log hander has been installed or when directly interacting with the user (e.g., in `configure`)
* Making functions for adding parser elements - this cleans up a lot of duplicate code and shortens each of the command functions quite a bit.
* Making a cleaner abstraction between `__main__` and `Evaluator` by making the latter only take a configuration dictionary and removing a lot of the kwargs (except `no_docker`, which can later be expanded to a target, e.g. one of `docker`, `host`, `aws`).
* It also updates documentation for this and using CUDA 9.
Fixes #478 
Closes #292 
It doesn't solve #505 , but would make that transition much easier.
=> Clean up of __main__ and interface with evaluator

armory/configuration.py, armory/data/utils.py, armory/utils/external_repo.py
Previously external repos were always downloaded on host so we didn't notice that we forgot to use SSL verification based on the armory config in order to download external repos.
=> Use SSL verification config in external repo download

armory/baseline_models/pytorch/sincnet.py
Used the clip's length as the seed for np.random before getting a random chunk in order to get deterministic results for benign LibriSpeech
=> Made SincNet results deterministic

armory/__main__.py, armory/data/model_weights.py, armory/paths.py, armory/scenarios/base.py, docs/docker.md
Fixes #511 
Fixes #506
Should be able to test with
```
armory download scenarios-set1.json --no-docker
```
This enables users to set the mode from paths as follows:
```
from armory import paths
paths.set_mode("host")
```
I find this preferable to directly modifying the `NO_DOCKER` flag. This way we can make additional pathing changes in the future for, say, AWS mode, in the future.
=> Download no docker

armory/scenarios/base.py, requirements.txt, setup.py
Adds a `--mongo` flag to the base scenario that takes the address of the MongoDB instance to send the results to.
Currently the exact same results are sent as are written to `.armory/outputs/`.
=> Optionally send evaluation results to a MongoDB instance

armory/docker/management.py
So went through a couple of iterations on deciding if we wanted to introduce docker configs to the scenario configurations. Ideally, we don't since they require special parsing from ECS task conversion. Looking into /dev/shm and the tempfs spec it doesn't appear to have negative consequences to hard code this as a higher value:
https://unix.stackexchange.com/questions/259823/if-tmpfs-has-bigger-size-than-your-ram-how-much-ram-does-it-use-are-applicatio
I tried setting this to 64GB (2x my laptops memory) and everything worked fine so shouldn't be an issue for systems < 16GB RAM. This guide also recommends increasing shm by default:
https://www.pugetsystems.com/labs/hpc/How-To-Setup-NVIDIA-Docker-and-NGC-Registry-on-your-Workstation---Part-5-Docker-Performance-and-Resource-Tuning-1119/ …
=> Increase default SHM size

armory/scenarios/poisoning_gtsrb_scenario.py, docs/configuration_files.md
Closes #582, with concurrent PR 46 in armory-examples.
=> Allow separate models for training on poisoned and cleaned datasets

armory/data/adversarial_datasets.py, armory/data/datasets.py, armory/data/pytorch_loaders.py, docker/pytorch/Dockerfile, tests/test_pytorch/test_framework_dataset.py
Closes #455 
Works for cifar10 and mnist. Some design decisions we'd need to make and then we can expand this to other datasets.
=> Initial PyTorch dataloaders from TFRecords

armory/eval/evaluator.py
Removes Windows incompatible colon from directory name. See also https://github.com/twosixlabs/armory/issues/636#issuecomment-645530025
=> Windows compatible output_dir/eval_id

docker/build.sh
Fixes #630 
This does two things:
1) Removes the direct build of the intermediate images `<framework>-base`, which were not used. (This caused additional computational due to improper caching.)
2) Reorders the cache arguments. (Framework-specific first, armory second). This should solve the rebuilding issue we were seeing before, since what happened (apparently) was that it would use armory as the cache and not use the framework-specific cache. Now, if all of the lines in the cache match, it will take the longer (framework-specific) one.
The most relevant thread I found was this comment: https://github.com/moby/moby/issues/26065#issuecomment-249046559
"Specifying multiple --cache-from images is bit problematic. If both images match there is no way(without doing multiple passes) to figure …
=> updated docker build

scenario_configs/librispeech_baseline_sincnet_adversarial.json
Update config for Librispeech preloaded attack to use "adversarial_perturbation" rather than "adversarial" as adversarial_key -- required for config to work after (#635).
=> Update config for Librispeech preloaded attack

armory/scenarios/base.py
The old MongoDB instructions work for the username / password authentication, provided those are passed with the mongodb url. The instructions are updated, and a regex is included in _save_to_mongo that will strip the username /password from the mongodb host name in the logs.
=> mongodb instructions updated

armory/__main__.py, armory/docker/management.py, armory/eval/evaluator.py, docs/command_line.md, docs/docker.md, docs/index.md, mkdocs.yml
Fixes #679 
Also enables `--root` command line arg to run the docker container as root instead of the current user, which is needed to run custom configs or containers that write to `/`.
=> Docker root and command line docs

armory/eval/evaluator.py
=> When using --no-docker, use same python executable as in subprocess

armory/__main__.py, armory/docker/host_management.py, armory/docker/management.py, armory/eval/evaluator.py, armory/scenarios/__init__.py, armory/scenarios/base.py, armory/scenarios/common.py
Modifies the base scenario to print a sentinel value before exiting cleanly. The ArmoryInstance that manages the container then checks for this value
As part of checking for the sentinel value, remove duplicate newlines from container log output
Closes #698
=> Exit with a non-zero status code if the scenario in armory run errors

armory/docker/management.py
Instead of checking if the last line from the container was the sentinel, check if the container emitted the sentinel ever. This provides robustness to warning messages being printed during container shutdown, after the sentinel is emitted, which has been observed in some situations
Closes #720
=> check for the sentinel value indicating clean container shutdown more robustly

docker/Dockerfile
Pins ART to 1.4.1_dev branch to resolve [import error](https://github.com/Trusted-AI/adversarial-robustness-toolbox/issues/607) when torch and kornia are not installed. Placeholder until ART 1.4.1 is released.
=> Update to ART 1.4.1 branch (placeholder until release)

docker/pytorch/Dockerfile, host-requirements.txt
Should `cudatoolkit` be updated as well? We're pinned to `10.1`, but `11.0.221` is available on Conda
Note that this PR may cause issues when we update ART to `1.4`, if they're pinned to a different version of `pytorch`
=> Update pytorch to `1.6.0` and torchvision to `0.7.0`

armory/baseline_models/keras/cifar.py, armory/baseline_models/keras/densenet121_resisc45.py, armory/baseline_models/keras/inception_resnet_v2.py, armory/baseline_models/keras/micronnet_gtsrb.py, armory/baseline_models/keras/mnist.py, armory/baseline_models/keras/resnet50.py, armory/baseline_models/keras/so2sat.py, armory/baseline_models/pytorch/cifar.py, armory/baseline_models/pytorch/mnist.py, armory/baseline_models/pytorch/resnet50.py, armory/baseline_models/pytorch/sincnet.py, armory/baseline_models/pytorch/ucf101_mars.py, armory/baseline_models/pytorch/xview_frcnn.py, armory/baseline_models/tf_graph/mnist.py, armory/utils/config_loading.py, armory/utils/config_schema.json, tests/test_pytorch/test_pytorch_models.py, tests/test_tf1/test_keras_models.py
Update all baseline models to expect to be given a path as produced by `maybe_download_weights_from_s3()` instead of a file name
Based on #657 
Fixes #646
=> Use maybe_download_weights_from_s3() when loading models

armory/data/adversarial_datasets.py
The apricot dataset uses 12 as the category_id for adversarial patches, which may be used for meaningful categories for other datasets. Add a lambda_map to make this category_id configurable.
=> Configurable magic number for Apricot dataset

armory/baseline_models/pytorch/xview_frcnn.py, armory/eval/evaluator.py, armory/paths.py, docs/docker.md, tests/conftest.py
Fixes #779 
Clears the defect by passing pass a TORCH_HOME of `…/saved_models/pytorch` into container execution.
I've left breadcrumbs in where we might allow a run-time override as suggested by @davidslater .
=> Fix TORCH_HOME to work in the container

armory/data/datasets.py, armory/data/pytorch_loader.py, tests/test_pytorch/test_framework_dataset.py, tests/test_tf1/test_framework_dataset.py
Closes #807 by 
1.  Throwing an error if the user selects pytorch or tf framework and applies a data or label preprocessing_fn
2.  For pytorch datasets, check if the labels are in dictionary format and, if so, convert each stored value that is a tensorflow tensor.
=> Fix pytorch loader

armory/baseline_models/keras/so2sat.py, armory/data/datasets.py
Closes #781 
We found the following minimum/maximum values for each channel, computed across the entire dataset.
```
SAR Channel 1, Min: -107.636246, Max: 67.136765
SAR Channel 2, Min: -107.636246, Max: 107.63296
SAR Channel 3, Min: -115.25347, Max: 115.00613
SAR Channel 4, Min: -114.72947, Max: 115.00594
Optical Channel 1, Min: 1e-04, Max: 2.8
Optical Channel 2, Min: 1e-04, Max: 2.8
Optical Channel 3, Min: 1e-04, Max: 2.8 
Optical Channel 4, Min: 1e-04, Max: 2.8001
Optical Channel 5, Min: 1e-04, Max: 2.8002
Optical Channel 6, Min: 1e-04, Max: 2.8003
Optical Channel 7, Min: 1e-04, Max: 2.8001
Optical Channel 8, Min: 1e-04, Max: 2.8005
Optical Channel 9, Min: 1e-04, Max: 2.8001
Optical Channel 10, Min: 1e-04, Max: 2.8
```
To minimize floating point errors, we scale SAR channels by 128 and …
=> Separate scaling for SAR/EO

armory/utils/config_loading.py, armory/utils/labels.py, scenario_configs/asr_deepspeech_baseline.json
=> Better ASR Labels

armory/baseline_models/pytorch/deep_speech.py
Fixes #856 
There is a more permanent solution in #805 , but that requires a 1.5 update in ART.
=> Save deep speech model weights in armory directory

armory/data/librispeech/librispeech_dev_clean_split.py, scenario_configs/asr_deepspeech_baseline_fgsm.json
Fixes #847 
Config for ASR using FGSM.
The other file is some weird lint thing. It passes black formatting, so I don't know.
=> working FGSM config for ASR + lint

armory/data/adversarial_datasets.py, armory/data/datasets.py, armory/data/digit/digit.py, armory/data/german_traffic_sign/german_traffic_sign.py, armory/scenarios/audio_asr.py, armory/scenarios/audio_classification.py, armory/scenarios/image_classification.py, armory/scenarios/poisoning_gtsrb_scenario.py, armory/scenarios/video_ucf101_scenario.py, docs/configuration_files.md, tests/test_docker/test_dataset.py, tests/test_pytorch/test_framework_dataset.py, tests/test_pytorch/test_pytorch_models.py, tests/test_tf1/test_framework_dataset.py, tests/test_tf1/test_keras_models.py, tests/test_tf1/test_tf1_models.py
Fixes #871 
This PR does a few related things:
1) Renames "split_type" to "split" to make it clear that it is verbatim what is given to TFDS load (same kwarg name)
https://www.tensorflow.org/datasets/api_docs/python/tfds/load
2) Modifies scenarios so that configs can override the train and eval splits. This enables TFDS slicing operations on them such as `"test[:10]"` or `"train_clean100+train_clean360+train_other500"`:
https://www.tensorflow.org/datasets/splits#examples
3) Adds additional parsing of splits to enable individual indexing for a specific data point, such as "test[355]", and indexing based off of a list, "test[[1, 4, 5, 7, 9]]". Under the hood, these are translated to single-element slices. Advanced slicing operations involving a `step` parameter, such as "test[10:20:2]" are …
=> Dataset index and slicing

armory/baseline_models/pytorch/ucf101_mars.py, armory/data/datasets.py, docs/datasets.md, scenario_configs/ucf101_baseline_finetune.json
Fixes #843 
Updates the dataset canonical preprocessing and mars-specific preprocessing to handle the 4 test samples of shape 226x400 (the rest are 240x320).
=> UCF101 shape bug

armory/scenarios/audio_asr.py, armory/scenarios/audio_classification.py, armory/scenarios/image_classification.py, armory/scenarios/outputs.py, armory/scenarios/video_ucf101_scenario.py, armory/utils/metrics.py, docs/metrics.md
Closes #848 
For targeted attacks, this will now compute the selected metrics two different ways:
1. Relative to the ground truth labels (i.e. a measure of the effectiveness of the defense).
2. Relative to the target labels (i.e. a measure of the effectiveness of the attack).
For untargeted attacks, only the first metric is computed.  We could compute the second metric in some cases, such as `1-accuracy` for classification problems, but the desired behavior is less obvious for other problem types (e.g. object detection).
=> Split metrics when targeted attack is present

armory/baseline_models/keras/densenet121_resisc45.py, armory/baseline_models/keras/inception_resnet_v2.py, armory/baseline_models/keras/resnet50.py, armory/baseline_models/pytorch/resnet50.py, scenario_configs/asr_deepspeech_baseline.json, scenario_configs/asr_deepspeech_baseline_fgsm.json
=> Fix Clip Values

armory/utils/metrics.py
Fixes #934
Let me know if this is what you're thinking. To test, try:
```
>>> from armory.utils import metrics
>>> import numpy as np
>>> metrics.snr(*[np.random.random((1, 400)) for i in range(2)]). # 1D inputs
[2.1268499851463973]
>>> metrics.snr(*[np.random.random((1, 20, 20, 3)) for i in range(2)]) # 3-channel image inputs
[2.0411371110126844]
```
It should work for any shape so long as the values are comparable.
=> SNR: remove constraint on 1D inputs

.github/workflows/ci_test.yml
flag ci_test workflow to allow manual execution
see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow to run once this is merged
=> allow manual execution of ci-test workflow

armory/data/adversarial_datasets.py, armory/data/datasets.py, armory/utils/config_loading.py, docs/configuration_files.md, tests/test_docker/test_dataset.py
Currently, you can add a numeric index to loading a dataset, like this:
```
import logging
import coloredlogs
coloredlogs.install(logging.DEBUG)
import numpy as np
from armory.data import datasets
ds = datasets.mnist("test", shuffle_files=False, index=None)
print(np.hstack([next(ds)[1] for i in range(10)]))
ds = datasets.mnist("test", shuffle_files=False, index=[1, 3, 5, 7, 9])
print(np.hstack([next(ds)[1] for i in range(5)]))
```
I need to check to make sure that:
I'd be happy for any thoughts at this point.
=> add indexing to datasets

armory/__main__.py, armory/arguments.py, docs/command_line.md, docs/configuration_files.md, tests/test_host/test_config_merge.py
Fixes #976 
Cross-pollinate sysconfig and command-line overrides from config into arguments and arguments back into config so that output records actual run-time parameters.
WIP because it needs formal tests across the 9 enumerated cases.
=> unify sysconfig and command line directives

docker/tf1/Dockerfile
Closes #1055 . This PR pins numpy to the version used in the official 0.13.0 release
=> Pin numpy version for TF1 image to avoid ART TensorFlowFasterRCNN error

armory/eval/plot.py, armory/scenarios/poisoning_gtsrb_clbd.py, armory/scenarios/poisoning_gtsrb_scenario.py, armory/utils/config_schema.json, armory/utils/metrics.py, tests/test_docker/test_metrics.py, tests/test_pytorch/test_pytorch_models.py, tests/test_tf1/test_tf1_models.py
This PR applies to average precision (AP) metrics that must be computed at once over all samples. It also involves some changes to the core `MetricList` and `MetricsLogger` classes, mostly in how they relate to these AP metrics.
(1) Refactor/reduce conditional logic specific to individual metrics in a way that isn't clean or very readable, see [here](https://github.com/twosixlabs/armory/blob/v0.13.0/armory/utils/metrics.py#L1264-L1298) and [here](https://github.com/twosixlabs/armory/blob/v0.13.0/armory/utils/metrics.py#L1312-L1362).
(2) Simplify input format to average precision metrics to take in a list of labels and a list of predictions. Currently they take in a list of lists of dicts (one list for each batch), which makes the code less clear (see …
=> refactor object detection metrics

armory/art_experimental/defences/jpeg_compression_normalized.py, armory/utils/config_loading.py, scenario_configs/apricot_frcnn_defended.json, scenario_configs/xview_frcnn_defended.json
(1) Closes #1058. This issue arose because during the loading of ART preprocessing defenses, the ART estimator's `all_framework_preprocessing` attribute needs to be updated. This is accomplished by calling the estimator's `set_params()` method.
(2) Closes #1059. The defense in  `art_experimental/defences/jpeg_compression_normalized.py` was using a `channel_index` kwarg which has been deprecated in ART. This defense, as well as associated configs, have been updated. The channel index defaults to a channels_last format which is how Armory loads data.
=> preprocessing defense fixes

docker/tf1/Dockerfile
(Same as #1079, but with hotfix branch name.) The tf1 container has a dated version of Tensorflow (1.15.0), which still has the following [bug](https://github.com/h5py/h5py/issues/1732) when h5py is >=3.0.0. The conda version of tensorflow still does not support tensorflow 1 >1.15.0. As a workaround can pin the h5py version to be <3.0.0.
=> Hotfix: Docker tf1 fix to allow tensorflow.keras to load h5 weights (fixes CI testing)

armory/art_experimental/attacks/sweep.py, armory/utils/config_loading.py, armory/utils/config_schema.json, armory/utils/metrics.py, docs/configuration_files.md, docs/sweep_attacks.md, mkdocs.yml, scenario_configs/gtsrb_scenario_clbd.json, scenario_configs/gtsrb_scenario_clbd_bullethole.json, scenario_configs/gtsrb_scenario_clbd_defended.json, scenario_configs/resisc45_baseline_densenet121_sweep_eps.json, scenario_configs/xview_frcnn_sweep_patch_size.json
Closes #1066.
Two other items that this PR includes:
1. Documenting the supported values for attack config `"type"` field and throwing a warning if an unexpected value is received
2. Adding `object_detection_mAP()` metric function. This simply calls the `object_detection_AP_per_class()` function and then returns the mean across each class. SweepAttacks enforce that metrics used to measure attack success return scalars, hence the reason this was included in this PR
=> sweep attacks

scenario_configs/gtsrb_scenario_bullethole.json
Add non-preloaded dirty-label backdoor attack with bullethole trigger - the preloaded dataset now will be deprecated.
=> Add non-preloaded dirty-label backdoor attack with bullethole trigger

armory/scenarios/utils.py
Given a dataset with only two splits - train and test, these utilities divide the train set into subsets following a generalized version of the logic from the Bullseye Polytope attack, which in turn borrows the logic from the Convex Polytope [attack](https://arxiv.org/pdf/1905.05897.pdf).
=> Dataset split utilities for bullseye polytope attack

armory/__main__.py, armory/data/datasets.py, docs/command_line.md
It turns out that most of the functionality was already done:
https://github.com/twosixlabs/armory/blob/dev/armory/data/datasets.py#L273-L337
With tests:
https://github.com/twosixlabs/armory/blob/dev/tests/test_docker/test_dataset.py#L71-L142
I just added hooks for the command line, `--index` and `--classes`, and updated the docs.
Will close the previous PR as there was unnecessary code there.
=> Dataset Indexing - Index and class filtering from command line

armory/art_experimental/attacks/carla_adversarial_texture.py
Fixed a bug in CARLA video patch attack that resulted in either a slightly misalignment between patch and green screen or a patch that's only partially perturbed.
=> fix carla video attack

armory/art_experimental/attacks/carla_adversarial_texture.py
Closes #1220. Instantiates new attack object each `generate()` call with the appropriate `patch_height`, `patch_width`, `x_min`, and `y_min`.
Per ART team, the current pattern of overwriting attributes might be challenging to maintain if future versions require changes or add extensions
=> refactor video tracking attack

armory/scenarios/carla_object_detection.py, armory/utils/metrics.py
=> measure CARLA adversarial performance using benign predictions as labels

.github/workflows/ci_test.yml
Uses `develop` instead of `dev` in CI build.
=> point ci build to develop branch instead of dev

.github/workflows/ci_test.yml, tests/test_pytorch/test_pytorch_models.py
The `pytest-pytorch` block of CI was causing the CI build machine to run out of resources. 
This uses the pytest "test names matching pattern" `-k` option to run the carla CI tests separately allowing the test https://github.com/mwartell/armory/actions/runs/1654197244 to complete successfully.
This is merging to master because it fixes a CI problem that all subordinate branches will see.
=> split carla tests onto their own CI runner

armory/baseline_models/pytorch/resnet18_bean_regularization.py, armory/utils/new_poisoning_metrics.py
Model weights will be emailed separately.
=> draft new poison metrics and associated interpretive model

armory/utils/export.py
Only boxes with score greater than 0.9 were being drawn on exported samples, but the carla metrics count all predictions with score greater than 0.5.  This matches the export function to the metrics.
=> Carla: export all relevant bboxes

armory/baseline_models/pytorch/deep_speech.py
This updates this baseline model file to:
a) properly save the model weights to armory data directory instead of tmp (due to update in ART)
b) remove unnecessary subclass due to `compute_loss` being implemented in ART.
=> update baseline to be up to date with ART

armory/docker/management.py
Fixes #1267 
Uses the `mount=` form of docker-py container creation instead of `volumes=` because the later cannot accept literal colons `:` in directory names.  Since armory mounts the expanded cwd, running armory in `/home/msw/foo:bar/` will fault.
The `mount=` form works properly if there is a colon. This is similar to the `docker --mount` and `--volumes` arguments.
=> Fix docker colons 1267

armory/baseline_models/pytorch/ucf101_mars.py, armory/data/datasets.py, scenario_configs/ucf101_baseline_finetune.json, scenario_configs/ucf101_baseline_pretrained_targeted.json, scenario_configs/ucf101_pretrained_flicker_defended.json, scenario_configs/ucf101_pretrained_flicker_undefended.json, scenario_configs/ucf101_pretrained_frame_saliency_defended.json, scenario_configs/ucf101_pretrained_frame_saliency_undefended.json, scenario_configs/ucf101_pretrained_masked_pgd_defended.json, scenario_configs/ucf101_pretrained_masked_pgd_undefended.json
Fixes #1150 
This change is computationally helpful, as it moves clipping to the beginning of the preprocessing pipeline instead of the model's forward pass (and implicitly, the gradient computation).
Can test the functionality directly with
```
import numpy as np
from armory.data import datasets
max_frames = 5
x,y = next(datasets.ucf101(batch_size=1, max_frames=max_frames))
assert x.shape[1] == max_frames
x,y = next(datasets.ucf101(batch_size=2, max_frames=max_frames))
assert x.dtype == np.object
assert all([x_i.shape[0] == max_frames for x_i in x])
```
Otherwise, the scenarios should work as before.
=> move ucf101 clipping to data

armory/data/adversarial/apricot_metadata.py, armory/data/adversarial_datasets.py, armory/utils/metrics.py
Currently, if you import `armory.utils.metrics`, it will end up importing `armory.data.adversarial_datasets` and `armory.data.datasets` in order to get a single constant, which actually takes some time and seems like an odd pattern.
Since we already have a metadata file for the other apricot constants, I am moving this constant to that file. Now `armory.utils.metrics` will only import that single metadata file, which is quite small.
=> Move apricot metadata to proper file

tests/conftest.py, tests/unit/test_logging.py
This uses the loguru suggested change to the pytest `caplog` mechanism for assertions on logging output. Sample use can be seen in tests/unit/test_logging.py.
=> add pytest loguru logcap fixure with tests

armory/art_experimental/attacks/carla_obj_det_patch.py, armory/art_experimental/attacks/carla_obj_det_utils.py, scenario_configs/carla_obj_det_dpatch_defended.json, scenario_configs/carla_obj_det_dpatch_undefended.json, scenario_configs/carla_obj_det_multimodal_dpatch_defended.json, scenario_configs/carla_obj_det_multimodal_dpatch_undefended.json
Updated `art_experimental carla_obj_det_patch` to attack both RGB and Depth.
For reference, I got the following results on `test` using `large` split (note, the multimodal defended model was trained to defend against RGB attack only, so ignore its performance on the updated attack)
- carla_obj_det_multimodal_dpatch_defended.json: 0.33 mAP / 42 hallucinations per image
- carla_obj_det_multimodal_dpatch_undefended.json: 0.34 mAP / 14 hallucinations per image
- carla_obj_det_dpatch_undefended.json: 0.18 mAP / 11 hallucinations per image
- carla_obj_det_dpatch_defended.json: 0.18 mAP / 9 hallucinations per image
=> For Issue #1375 - Eval5 carla obj det robust dpatch

armory/__init__.py
Fixes #1437 
May not be the best long-term fix, but can revisit as we break out the armory runtime from the outer component.
=> shortcircuit init when querying version

armory/art_experimental/attacks/carla_obj_det_patch.py
@lcadalzo Minor update to remove dependency on `shape`, `cc_ground_truth`, and `cc_scene` keywords in Eval5 adversarial datasets
=> Minor update to CARLA Robust Dpath attack 

armory/art_experimental/defences/video_compression_normalized.py, scenario_configs/eval1-4/ucf101/ucf101_pretrained_flicker_defended.json
Fixes #1471 
The error was due to using a PyTorch framework attack on a non-PyTorch defense. Changing to the PyTorch defense (plus a little typo change for consistency) fixed the issue.
=> Fix Flicker defended config

armory/__init__.py, armory/art_experimental/__init__.py, armory/baseline_models/__init__.py, armory/data/__init__.py, armory/delayed_imports.py, armory/scenarios/__init__.py, armory/version.py
This PR attempts to reduce the import time of armory. It does this in two ways:
1) Generates the `__version__` only if asked for.
2) Delays import of torch, tensorflow, and art until a submodule needing them (`art_experimental`, `baseline_models`, `data`, `scenarios`) is loaded. Also adds a logging message to that effect.
Once `tiga` is merged in, the time lag for version generation should be fairly minimal, but this will reduce things for now.
=> improve import time

.github/workflows/release.yml, docker/build.py
Fixes #1531
This updates the build script to not require pip installation. We already require it to be run from the root of the armory repo, so it seems weird to require a pip install to simply import armory.
=> Release fix

armory/data/adversarial_datasets.py, armory/data/datasets.py
Addresses #1543. Done so via a `"max_frames"` dataset kwarg that defaults to `None` and can be set from the dataset config as such:
```
"dataset": {
"batch_size": 1,
"eval_split": "dev",
"framework": "numpy",
"module": "armory.data.adversarial_datasets",
"name": "carla_video_tracking_dev",
"max_frames": 30
},
```
=> Clip CARLA video tracking inputs (and labels, correspondingly)

armory-base-requirements.txt, docker/Dockerfile-pytorch, docker/Dockerfile-pytorch-deepspeech, docker/Dockerfile-tf2, host-requirements.txt
Closes #1549. Leaving as `WIP` until 1.10.3 is released, at which point I'll manually trigger CI
=> updating to ART 1.10.3

.github/workflows/release.yml
Reverts twosixlabs/armory#1588
This branch should have been based off master, but brought in all the dev_0.15.4 changes, so needs to be reverted and abandoned.
=> Revert "release pypi wheels and dockerhub images via workflow dispatch"

.github/workflows/release.yml
we are trying to build the release but the push to pypi.org already succeeded, skip it for now.
=> omit push to pypi temporarily

.github/workflows/release.yml
This reverts commit d1fb9b431ce2a9482fd94ab4953544abd07e43a7.
Because github actions only sees CI changes on master, we had to add that commit as a workaround and back it out.
=> Revert "omit push to pypi temporarily"

armory/__main__.py
This makes two small changes:
1) Instead of "launch" defaulting to a no-op and shutting down without `--interactive` or `--jupyter` provided, it now defaults to `--interactive`:
```
armory launch pytorch
```
2) Instead of "exec" erroring out when no command line args are given, it defaults to a no-op.
```
armory exec pytorch --
```
Exec will still error if the `--` delimiter is not present.
=> Launch / Exec - better defaults

.github/workflows/2-test-stand-alone.yml, pyproject.toml
The `[all]` target causes 2+ hour pip installations because it is computationally hard when versions are unpinned. Also, we don't need such an installation.
=> remove [all] target from pyproject and CI because it lags CI badly

docker/Dockerfile-base, docker/Dockerfile-pytorch-deepspeech, docker/Dockerfile-tf2, pyproject.toml
Bare minimum fixes to make `tf2` and `pytorch-deepspeech` containers build properly. Goal is to enable armory release on Friday, as the bigger updates will likely need to wait (e.g., removing the `tf2` and `pytorch-deepspeech` containers).
This removes the TF Object Detection API dependency from both the `tf2` dockerfile and `pyproject.toml`, as it is not actively being supported and causes dependency hell.
`librosa` is now in base, so I removed its install from the `pytorch-deepspeech` dockerfile.
The only other changes were to remove version information from `pyproject.toml` except where explicitly needed.
=> buildable docker containers

README.md, docker/Dockerfile-carla-mot, docs/no_docker_mode.md
Closes:
- [Fix links to CI badge and project logo for pypi and readthedocs #1679 ](https://github.com/twosixlabs/armory/issues/1679)
- [find a way to avoid a duplicate armory installation in Dockerfile-carla-mot #1671](https://github.com/twosixlabs/armory/issues/1671)
- `README.md` now links assets directly to the TwoSix Armory repo.
- `docs/no_docker_mode.md` elaborate on the environment setup steps.
- `docker/Dockerfile-carla-mot` remove initial image configuration; now inherits updated `pytorch` base image.
=> Documentation & Dockerfile cleanup/fixes

armory/docker/management.py, armory/eval/evaluator.py
Centralizes image lookup to the `docker` module.
I am moving `ensure_image_present` out of `armory/eval/evaluator.py` and into `armory/docker/management.py`  in order to decouple the two modules; partially.
=> Decouple evaluator and magement

tools/pre-commit.sh
Without `HEAD`, this compares the current to the staged commits.
=> update commit hook

armory/metrics/task.py
Addresses https://github.com/twosixlabs/armory/issues/1769
Relable function would return subarrays of type `float64` if they are empty which caused issues when passed into the HOTA function which expected it to be of type `int`. Change utilizes the empty array's dtype for consistency.
=> Retain data type for arrays passed into "relable" function

armory/utils/config_schema.json
This PR adds structure to the dataset config schema. A couple decisions that were made:
1. it requires that ~~at least one of `"test"` and `"train"` is present underneath `"dataset"`~~
edit: I had it this way, then went back to requiring `"test"`, since there is no "train-only" mode in Armory
2. It allows _only_ the keys `"test"` and `"train"` to go underneath `"dataset"` (via `"additionalProperties": false`) . So if you use a config from current master branch, it will fail with `Could not validate config: Additional properties are not allowed ('module', 'name', 'batch_size', 'framework' were unexpected) @ dataset`
3. for the objects that `"test"` and `"train"` map to, it requires the following two keys: `"batch_size"` and `"name"`
=> update dataset config schema

armory/scenarios/scenario.py, scenario_configs/eval1-4/cifar/cifar10_baseline.json, scenario_configs/eval1-4/mnist/mnist_baseline.json
1. This fix gets rid of the `TypeError: art.estimators.classification.pytorch.PyTorchClassifier.fit_generator() got multiple values for keyword argument 'nb_epochs'` when running the cifar config, since `epochs` is now specified in dataset config rather than model config
2. This PR also fixes a bug where the error above occurs when `--check` is set, since the `scenario.py` logic needed to be updated to modify the _dataset_ config rather than model config when `--check` is set.
3. Same as (1) but for mnist config
=> fixing cifar config to comply with recent changes to tfdsv4 branch

.github/workflows/scenario-runner.yml
This repoints the scenario-runner CI to execute on our self-hosted runner because the Github hosted runners are too small for those tests.
=> runs scenario checks on self-hosted runner

armory/scenarios/poisoning_sleeper_agent.py
Corrections: scale the patch to [0,1], and find the correct poison indices.
Note: running the current configs will return low attack success because the attack parameters are tuned for a slightly different resnet version.
=> Sleeper agent fix

armory/datasets/build.py, armory/datasets/cached_datasets.json, armory/datasets/config_load.py, armory/datasets/download.py, armory/datasets/load.py, armory/datasets/package.py, armory/datasets/preprocessing.py
Updated code for packaging, uploading, and loading datasets for armory run to account for cases where datasets have subdirectories. User can specify the desired subdirectory with optional `config` as kwarg for `test` or `train` of `dataset` in config json file. `config` value must match the name of one of the subdirectories - if `config` is not specified, `tfds.builder` seems to refer to `imagenette/.config/metadata.json` for the `config` value. This update assumes that all `tfds` datasets have `.config/metadata.json` if the dataset has subdirectories. We are working off of `v4.6.0` of `tfds` - code may need to be updated should `tfds` version change.
Note: When testing `imagenette`, I could tell that a different subdirectory was being used by the number of samples from `armory` logs
=> Updated imagenette

armory/baseline_models/pytorch/resnet18.py, scenario_configs/eval6/poisoning/audio_dlbd/audio_p00_undefended.json, scenario_configs/eval6/poisoning/audio_dlbd/audio_p01_undefended.json, scenario_configs/eval6/poisoning/audio_dlbd/audio_p05_undefended.json, scenario_configs/eval6/poisoning/audio_dlbd/audio_p10_undefended.json, scenario_configs/eval6/poisoning/audio_dlbd/audio_p20_undefended.json, scenario_configs/eval6/poisoning/audio_dlbd/audio_p30_undefended.json, scenario_configs/eval6/poisoning/audio_dlbd/baseline_defenses/audio_p10_activation_defense.json, scenario_configs/eval6/poisoning/audio_dlbd/baseline_defenses/audio_p10_dpinstahide.json, scenario_configs/eval6/poisoning/audio_dlbd/baseline_defenses/audio_p10_perfect_filter.json, scenario_configs/eval6/poisoning/audio_dlbd/baseline_defenses/audio_p10_random_filter.json, scenario_configs/eval6/poisoning/audio_dlbd/baseline_defenses/audio_p10_spectral_signature_defense.json, scenario_configs/eval6/poisoning/sleeper_agent/baseline_defenses/cifar10_sleeper_agent_p10_activation_defense.json, scenario_configs/eval6/poisoning/sleeper_agent/baseline_defenses/cifar10_sleeper_agent_p10_dpinstahide.json, scenario_configs/eval6/poisoning/sleeper_agent/baseline_defenses/cifar10_sleeper_agent_p10_perfect_filter.json, scenario_configs/eval6/poisoning/sleeper_agent/baseline_defenses/cifar10_sleeper_agent_p10_random_filter.json, scenario_configs/eval6/poisoning/sleeper_agent/baseline_defenses/cifar10_sleeper_agent_p10_spectral_signatures_defense.json, scenario_configs/eval6/poisoning/sleeper_agent/cifar10_sleeper_agent_p00_undefended.json, scenario_configs/eval6/poisoning/sleeper_agent/cifar10_sleeper_agent_p01_undefended.json, scenario_configs/eval6/poisoning/sleeper_agent/cifar10_sleeper_agent_p05_undefended.json, scenario_configs/eval6/poisoning/sleeper_agent/cifar10_sleeper_agent_p10_undefended.json, scenario_configs/eval6/poisoning/sleeper_agent/cifar10_sleeper_agent_p20_undefended.json, scenario_configs/eval6/poisoning/sleeper_agent/cifar10_sleeper_agent_p30_undefended.json, scenario_configs/eval6/poisoning/sleeper_agent/cifar10_sleeper_agent_p50_undefended.json
Sleeper Agent doesn't work very well with the resnet18 already in armory.  Rather than attempt to tune hyperparameters, the poisoning group desired us to add this resnet version on which we know the attack succeeds.
=> Add sleeper agent resnet

armory/metrics/task.py, armory/scenarios/carla_object_detection.py, docs/metrics.md
Mike's description of the error from slack:
> it seems that per example metrics are always collected for OD scenarios even if ```metric -> record_metric_per_sample``` is ```False```. In addition, with the exception of ```AP_per_class```, the other metrics no longer report the mean statistic even if ```metric -> mean``` is ```True```.
This is essentially because the ```GlobalMeter``` class used for ```@populationwise``` metric functions assumes that the functions already return the mean over all samples.  This is true for ```AP_per_class```, but not the others.
Easy fix: just have the metric functions return the mean over all samples.  This seems to be what the writer of this code (David) expected.
But that leaves questions about why the carla OD functions are marked @populationwise in the …
=> Carla metrics bug fix

armory/metrics/__init__.py
See https://github.com/twosixlabs/armory/issues/1895.
=> Add verbose error message when importing armory.metrics without the proper dependencies installed.

armory/baseline_models/tf_graph/audio_resnet50.py, armory/data/adversarial_datasets.py, armory/data/datasets.py, armory/utils/config_loading.py
A few small unrelated improvements.
1. Raise an error if num-eval-batches is too large for dataset, fixing #1893 
2. Correct some docstrings and error messages for a few carla datasets
3. Add a decorator to the audio resnet model, cutting training time in half
=> Assorted improvements

pyproject.toml
Tfds version 4.9.0 has trouble importing on macos apparently, causing problems with our github tests.  See this [issue](https://github.com/tensorflow/datasets/issues/4852) for some context. 
We should be able to dodge this problem by not using that tfds version
=> avoid tfds version 4.9.0

armory/data/cached_s3_checksums/minicoco.txt, armory/data/cached_s3_checksums/mscoco_poisoning.txt, armory/data/datasets.py, armory/data/minicoco/minicoco.py, armory/data/mscoco/mscoco_poisoning.py, docs/datasets.md, tests/end_to_end/test_e2e_datasets.py
For object detection poisoning scenario
=> Eval7 - MSCOCO Poisoning Dataset

armory/metrics/__init__.py
Including caught error to better inform user when collecting dependencies without installing via `.[engine]`
=> Adding import error message to reported error

tools/pre-commit.sh
Removes the ` --indent=4` option until Python 3.8 support is dropped.
=> Remove unsupported option from precommit hooks

armory/eval/evaluator.py
I believe this retains the existing behavior when using docker.
For no-docker mode, this sets CUDA_VISIBLE_DEVICES to the list of gpus, if specified, or to -1 if the gpu is not to be used.  
It still defaults to using all gpus if use_gpu is True but no gpus are specified.
@christopherwoodall @jprokos26 Do you have any comments about this approach?  Any cases I'm overlooking?
Should fix #1923 and #1902.  Does not address #1922.
=> set cuda devices for no-docker mode

armory/art_experimental/attacks/carla_obj_det_adversarial_patch.py
Addresses #1930 
Searches for `patch_base_image` in more than one place:
1. Check if file exists in module path
2. Check if file exists in `armory.paths.runtime_paths().cwd`
3. Check if supplied `patch_base_image` is actually a url to an image we can download
Else fail
=> Add support for patch_base_image when not running locally

armory/scenarios/poisoning_obj_det.py, scenario_configs/eval7/poisoning/obj_det_dlbd_GMA.json, scenario_configs/eval7/poisoning/obj_det_dlbd_OGA.json, scenario_configs/eval7/poisoning/obj_det_dlbd_RMA.json
=> Minor BadDet improvements

docs/configuration_files.md
At least one performer experienced confusion about the ```local_repo_path``` variable; I think this should help.
=> clarify local repo path in config documentation

armory/scenarios/scenario.py
Fixes #1333.  Ensure that the config saved in the results json is identical to the initiating config.  In some cases the scenario, attack, or model may modify it.
=> Save original config

armory/art_experimental/attacks/carla_obj_det_patch.py, armory/baseline_models/pytorch/yolov3.py, armory/data/adversarial_datasets.py, armory/data/datasets.py, armory/metrics/poisoning.py, armory/scenarios/poison.py, armory/scenarios/poisoning_obj_det.py, armory/utils/labels.py
This pull request serves to address both `isort` errors and `E721` errors that surfaced following a recent merge into the `develop` branch. 
**Details of Changes:**
1. **Resorting Imports:** To eliminate `isort` errors, the imports have been resorted.
2. **Refining Type Checks:** The `E721` errors were resolved by refining our type checks.
Please review the changes and provide your feedback.
=> Resort imports after merge

armory/art_experimental/attacks/sweep.py, armory/data/datasets.py
To fix #1971, the three references to ```np.object``` are replaced with ```object```, as advised by the error statement:
> To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
=> Remove np.object references

armory/art_experimental/attacks/carla_obj_det_adversarial_patch.py
Makes it so you can put `patch_base_images` for carla od adv patch in any folder added to `local_repo_dir` in config.
=> iterate through sys.path instead of just checking cwd

armory/scenarios/poisoning_obj_det.py
ART has [corrected](https://github.com/Trusted-AI/adversarial-robustness-toolbox/pull/2143) an off-by-1 situation so it no longer needs to be accounted for here.
=> OD poison update

armory/data/datasets.py
See #1974.  It seems that some were overlooked
=> remove additional np.object references
